---
title: "Searches of common jobs: women tend to appear lower than men"
description: |
  A replication of the graph made by Pew Research Center about the topic and another proposal.
categories: "2022"
author: Mario Yanes
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggeasy)

df <- data.frame(Profession = c("CEO", "Professor", "Electrical engineer", "Security guard", "Banker", "Clergy", "Industrial engineer", "Bartender", "Musician", "Chef", "Movie director", "Police", "Athlete", "Medical scientist", "Physician", "Pharmacist", "Nurse", "Clerk", "Customer service rep.", "Housekeeper"),
                 Male = c(2, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3, 4, 4, 4, 6),
                 Female = c(16, 13, 10, 8, 9, 8, 7, 7, 6, 6, 6, 5, 5, 4, 3, 3, 4, 3, 2, 2),
                 position = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
                 position2 = c(3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 4, 2, 2, 2, 3, 3),
                 position3 = c(4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 4, 3, 5, 5, 4),
                 position4 = c(5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 5),
                 position5 = c(6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 6, 6, 7, 7, 7),
                 position6 = c(7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 8, 8, 8),
                 position7 = c(8, 8, 8, 9, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 9, 9, 9),
                 position8 = c(9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 10, 10, 10),
                 position9 = c(10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10, 10, 11, 11, 11),
                 position10 = c(11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 12, 12, 12),
                 position11 = c(12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12, 12, 13, 13, 13),
                 position12 = c(13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13, 14, 14, 14),
                 position13 = c(14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 14, 14, 15, 15, 15),
                 position14 = c(15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 16, 16, 16),
                 position15 = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 16, 16, NA, NA, NA)
                 )

```


```{r}

p <- ggplot(df, aes(y=Profession)) + 
  geom_tile(aes(x=Male), fill="orange", color = "orange", width = 0.35, height = 0.7) + 
  geom_tile(aes(x=Female), fill="purple", color = "purple", width = 0.35, height =0.7) +
  geom_tile(aes(x=position), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position2), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position3), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position4), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position5), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position6), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position7), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position8), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position9), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position10), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position11), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position12), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position13), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position14), fill="white", color = "grey", width = 0.35, height = 0.7) +
  geom_tile(aes(x=position15), fill="white", color = "grey", width = 0.35, height = 0.7) +
  scale_fill_manual(values=c(position ="white",
                             Male ="orange",
                             Female = "purple")) +
  scale_y_discrete(limits = rev(df$Profession), expand = expansion(mult = c(0, 0.1))) +
  #scale_x_discrete(limits = c(0, 16), breaks = c(1, 4, 8, 12, 16)) +
  labs(
    x = "",
    y = "",
    title = "Women appear lower in image\nsearch results for common jobs\nacross countries",
    subtitle = "Average position of the first man or woman\nin image search results for ... ",
   # caption = 'Source: Pew Research Center analysis of Google Image\n Search data from 18 countries. Image searches were\n conducted July7.Sept. 13, 2018. Images returned by\n searches conducted at other times may differ.\n "Gender and Jobs in Online Image Searches"'
  ) +
  annotate("text", x = 2, y = 21, label = "Male", size = 3, color = "orange", fontface = 2, family = "Arial") +
  annotate("text", x = 16, y = 21, label = "Female", size = 3, color = "purple", fontface = 2, family = "Arial") +
  annotate("rect", xmin = 3.05, xmax = 3.2, ymin = 4.65, ymax = 5.3, alpha = 1, color = "orange", fill = "orange") +
  annotate("rect", xmin = 4.05, xmax = 4.2, ymin = 3.65, ymax = 4.3, alpha = 1, color = "orange", fill = "orange") +
  #annotate("text", x = 0.5, y = 0.5, label = "1st", size = 2, color = "grey") +
  theme_light() 

p + theme(
  panel.background = element_blank(),
  panel.grid = element_line(size = 0.25, color = "white"),
  axis.ticks = element_blank(),
  axis.line = element_blank(),
  panel.border = element_blank(),
  axis.text = element_text(family = "Times New Roman"),
  #axis.text.x = element_blank(),
  plot.title = element_text(face = "bold", family = "Arial", hjust = 0),
  plot.subtitle = element_text(color = "grey", face = "italic", family = "Times New Roman", hjust = 0, vjust = 4),
  plot.caption = element_text(hjust = 0)
) 


```










