---
title: "China Dissent"
description: |
  Representing social dissent in China geospatially and by issue.
categories: "2022"
author: Gabriel Rodríguez Molina
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---


```{r include=FALSE}
library (distill)
library (tidyverse)
library (tmap)
library (sf)
library(ggplot2)
library(ggtext)

## read data
chinacsv <- read_delim ("dissent_last.csv", delim=",", skip=0) 

## creating codes to join the data and the map
chinadissent <- chinacsv %>% 
                  mutate (
                    code = case_when(
                      province %in%  c("Anhui") ~ "0" ,
                      province %in%  c("Fujian") ~ "1" ,
                      province %in%  c("Gansu") ~ "2" ,
                      province %in%  c("Guangdong") ~ "3" ,
                      province %in%  c("Guangxi") ~ "4" ,
                      province %in%  c("Guizhou") ~ "5" ,
                      province %in%  c("Hainan") ~ "6" ,
                      province %in%  c("Hebei") ~ "7" ,
                      province %in%  c("Heilongjiang") ~ "8" ,
                      province %in%  c("Henan") ~ "9" ,
                      province %in%  c("Hubei") ~ "10" ,
                      province %in%  c("Hunan") ~ "11" ,
                      province %in%  c("Inner Mongolia") ~ "12" ,
                      province %in%  c("Jiangsu") ~ "13" ,
                      province %in%  c("Jiangxi") ~ "14" ,
                      province %in%  c("Jilin") ~ "15" ,
                      province %in%  c("Liaoning") ~ "16" ,
                      province %in%  c("Shaanxi") ~ "17",
                      province %in%  c("Shandong") ~ "18",
                      province %in%  c("Shanxi") ~ "19",
                      province %in%  c("Sichuan") ~ "20",
                      province %in%  c("Tibet") ~ "21",
                      province %in%  c("Yunnan") ~ "22",
                      province %in%  c("Zhejiang") ~ "23",
                      province %in% c("Qinghai") ~ "24",
                      province %in% c("Xinjiang") ~ "25",
                      province %in% c("Ningxia") ~ "26"
                      )
                  )  %>% 
                  select(code) %>% 
                  mutate(across(c(code), as.numeric)) %>% 
                  count(code) %>% 
                  drop_na() 

## code for the map
china_map <- st_read("province.shp")

china_map1 <- china_map  %>% mutate (
                  code= case_when( 
                            NAME_PINGY %in% c("Anhui Sheng") ~ "0",
                            NAME_PINGY %in% c("Fujian Sheng") ~ "1",
                            NAME_PINGY %in% c("Gansu Sheng") ~ "2",
                            NAME_PINGY %in% c("Guangdong Sheng") ~ "3",
                            NAME_PINGY %in% c("Guangxizhuangzu Zizhiqu") ~ "4",
                            NAME_PINGY %in% c("Guizhou Sheng") ~ "5",
                            NAME_PINGY %in% c("Hainan Sheng") ~ "6",
                            NAME_PINGY %in% c("Hebei Sheng") ~ "7",
                            NAME_PINGY %in% c("Heilongjiang Sheng") ~ "8",
                            NAME_PINGY %in% c("Henan Sheng") ~ "9",
                            NAME_PINGY %in% c("Hubei Sheng") ~ "10",
                            NAME_PINGY %in% c("Hunan Sheng") ~ "11",
                            NAME_PINGY %in% c("Neimenggu Zizhiqu") ~ "12",
                            NAME_PINGY %in% c("Jiangsu Sheng") ~ "13",
                            NAME_PINGY %in% c("Jiangxi Sheng") ~ "14",
                            NAME_PINGY %in% c("Jilin Sheng") ~ "15",
                            NAME_PINGY %in% c("Liaoning Sheng") ~ "16",
                            NAME_PINGY %in% c("Shaanxi Sheng") ~ "17",
                            NAME_PINGY %in% c("Shandong Sheng") ~ "18",
                            NAME_PINGY %in% c("Shanxi Sheng") ~ "19",
                            NAME_PINGY %in% c("Sichuan Sheng") ~ "20",
                            NAME_PINGY %in% c("Xizang Zizhiqu") ~ "21",
                            NAME_PINGY %in% c("Yunnan Sheng") ~ "22",
                            NAME_PINGY %in% c("Zhejiang Sheng") ~ "23",
                            NAME_PINGY %in% c("Xinjiangweiwu'erzu Zizhiqu") ~ "25",
                            NAME_PINGY %in% c("Qinghai Sheng") ~ "24",
                            NAME_PINGY %in% c("Ningxiahuizu Zizhiqu") ~ "26"
                       ))   %>%
                      mutate(across(c(code), as.numeric)) %>% 
                      filter(NAME_PINGY != "Taiwan Sheng")
         
         
join_map_data <-  china_map1 %>% left_join(chinadissent, by="code") %>% select(COUNT, geometry)
```


```{r include=FALSE}

## data forn the second chart

x <- c("COVID-19 pandemic policies", "Delayed housing project","State violence", "Fund withdrawal", "Pay and benefits"  ,"Building disputes","School disputes", "Land rights", "Corruption", "Fraud", "Others")

china_data <- chinacsv %>% 
                transmute (
                  Date=`beginning date`,
                  reason_dissent = case_when( 
                    issue %in% c("fraud", "fraud, building quality", "fraud, contract breach", "fraud, corruption",
                              "fraud, investment disputes", "fraud, land rights", "fraud, land rights, corruption",
                              "fraud, property management disputes", "fraud, school district disputes",
                              "fraud, state violence", "fraud, state violence, corruption") ~ "Fraud",
                    issue %in% c("delayed housing project", "delayed housing project, building quality",
                              "delayed housing project, fraud","delayed housing project, project plan violation",
                              "delayed housing project, school district disputes", 
                              "delayed housing project, fraud, building quality") ~ "Delayed housing project",
                    issue %in% c("pay and benefits") ~ "Pay and benefits",
                    issue %in% c("COVID-19 pandemic policies", "COVID-19 pandemic policies, censorship", 
                              "COVID-19 pandemic policies, pay and benefits",
                              "COVID-19 pandemic policies, political change",
                              "COVID-19 pandemic policies, state violence",
                              "COVID-19 pandemic policies, censorship, political change", 
                              "COVID-19 pandemic policies, school health and safety", 
                              "COVID-19 pandemic policies, utility issues") ~ "COVID-19 pandemic policies",
                    issue %in% c("school bullying", "school district disputes",
                              "school district disputes, building quality", 
                              "school district disputes, building quality, service and management Issues",
                              "school policy") ~ "School disputes",
                    issue %in% c("building quality", "building quality, illegal property handover",
                              "building quality, property pricing") ~ "Building disputes",
                    issue %in% c("fund withdrawal freeze", "fund withdrawal freeze, corruption") ~ "Fund withdrawal",
                    issue %in% c("land rights", "land rights, corruption", "land rights, project plan violation") ~ 
                                  "Land rights",
                    issue %in% c("state violence", "state violence, land rights, corruption", 
                                 "state violence, verdict disputes", "state violence, verdict/sanction disputes"
                                 ) ~ "State violence",
                    issue %in% c("corruption", "corruption, abusing authority") ~ "Corruption",
                    issue %in% c("abusing authority", "agricultural rights","confiscation of assets",
                              "debt disputes", "drug safety", "environmental pollution or damage", 
                              "family policies", "missing persons","food safety", "forced eviction", "freedom of belief", 
                              "illegal property handover", "interior finish disputes", "occupational injury", 
                              "occupational safety", "personal safety", "petition rights", "political change", "poverty",
                              "project plan violation", "property management disputes", 
                              "property management disputes, environmental pollution or damage", 
                              "property pricing", "utility issues","verdict disputes", "video games", "censorship",
                              "investment disputes", "medical disputes", "contract breach", "family policies, 
                              missing persons", "verdict disputes", "product safety", "investment dispute", 
                              "service and management Issues", "school health and safety", "verdict/sanction disputes",
                              "women's rights") ~ "Others" 
                              )
                            ) %>%
                    drop_na() %>%
                    group_by(reason_dissent,Date) %>%
                    count() %>%
                    filter(Date >="2022-09-01") %>% 
                    group_by(reason_dissent) %>% 
                    mutate(cumulative_n = cumsum(n)) %>% 
                    transmute(
                          reason_dissent = factor (reason_dissent, levels = x),
                          cumulative_n,
                          Date)

# map

final_map <- join_map_data %>% ggplot() +
  geom_sf(aes(fill=COUNT), color="white",lwd=0.2, )  + 
  coord_sf(ylim=c(-1.7e+06, 2e+06), xlim=(c(-3.3e+06, 2e+06)))+
labs(
    fill=quote(bold("By province")),
    title = quote(bold("Do you hear the people sing?")),
    subtitle =("<span style='font-size: 10pt; font-family:Helvetica;'>China, number of protests</font><br>
                <span style='font-size: 9pt; font-family:Helvetica;'> September 1st to December 31th, 2022</font>")
    ) + 
  theme(
        plot.title = element_text(size = 12, family="Calibri", hjust=-0.015),
        plot.subtitle = element_markdown(lineheight=1.5, hjust=-0.01),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        legend.direction = "horizontal",
        legend.text = element_text(size=9, family="Helvetica"),
        legend.key.height = unit(0.18, 'cm'),
        legend.key.size = unit(0.6, 'cm'),
        legend.position = c(0.125,0.89),
        legend.title = element_text(size=9, family="Helvetica"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.spacing.x = unit(8.0, 'cm')
        ) +
  guides(
        fill = guide_colorbar(title.position = "top"))+
  scale_fill_binned(
        breaks = c(75, 100, 125, 150),
        low = "#C7E6FD", high = "#004776", 
        na.value="#d6d6d6",
        limits=c(50, 175)
            )

# second plot

cols <- c("#146c9b", "#eacbab", "#d49c4c", "#acdbdb" , "#040404","#9c947c" , "#ce9f5d", "#498caa", "#546466","#729499" )


final_plot<-ggplot(china_data) +
  aes(Date,cumulative_n) +
  ggstream::geom_stream(
      aes(fill=reason_dissent),
      type="proportional")+
  labs(
      title=quote(bold("Anti-lockdown protests boost due to zero-Covid strategy")),
      fill=quote(bold("By Issue")),
      caption = ("Source: Freedom's House China Dissent Monitor"),
      y = quote(bold("Percentage of protests")))+
  theme(
      plot.title = element_text(size = 12, family="Calibri", 
                                margin=margin(0,0,5,0)),
      panel.background = element_blank(),
      plot.margin=unit(c(0,0,0,0),"cm"),
      plot.title.position = "plot",
      axis.text.y = element_text(hjust=0, size=11, family="Helvetica", color="black"),
      axis.text.x = element_text(size=11, 
                                 family="Helvetica", color="black"),
      axis.title.x = element_blank(),
      aspect.ratio = 0.68,
      plot.caption = element_text(hjust = -1.25, size=10, color="grey"),
      legend.text = element_text(size=9, family="Helvetica"),
      legend.key.height = unit(0.27, 'cm'),
      legend.key.width  = unit(0.27, 'cm'),
      legend.key.size = unit(0.9, 'cm'),
      legend.position = "bottom",
      legend.title = element_text(size=9, family="Helvetica"))+
  scale_x_date(date_breaks = "months", date_labels = "%m-%Y", expand = c(0.01, 0))+
  scale_y_continuous(labels= c("0%", "25%", "50%", "75%", "100%"), expand = c(0.10, 0))+
  guides(fill = guide_legend(title.position = "top"))+
  scale_fill_manual(values = cols)
```


```{r echo=FALSE, fig.align='center'}
final_map
```
```{r echo=FALSE, fig.align='center'}
final_plot
```









