---
title: "Recreating a Pew Research graph"
description: |
  In this post I recreate a Pew Research graph and propose an alternative visualisation of the data.
categories: "2022"
author: Eliseo Garilleti
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r}
library(tidyverse)
library(readxl)
library(ggpubr)
library(gridExtra)
```



```{r}
dataviz <- read_xlsx("Data/proyecto.xlsx")
```

```{r}
dataviz_long <- dataviz %>% 
  pivot_longer(cols = c(2,3),
               names_to = "Eco_perception",
               values_to = "Proportion") 

datalong_alt <- dataviz_long %>% 
  mutate(zone = case_when(Country == "Poland" ~ 1,
                          Country == "Hungary" ~ 1,
                          Country == "Germany" ~ 1,
                          Country == "Greece" ~ 1,
                          Country == "Italy" ~ 1,
                          Country == "France" ~ 1,
                          Country == "Netherlands" ~ 1,
                          Country == "Sweden" ~ 1,
                          Country == "Spain" ~ 1,
                          Country == "Belgium" ~ 1,
                          Country == "UK" ~ 2,
                          Country == "U.S." ~ 2,
                          Country == "Canada" ~ 2,
                          Country == "Australia" ~ 2,
                          Country == "Malaysia" ~ 3,
                          Country == "South Korea" ~ 3,
                          Country == "Singapore" ~ 3,
                          Country == "Japan" ~ 3),
         zone_2 = case_when(Country == "Poland" ~ 1,
                            Country == "Hungary" ~ 1,
                            Country == "Germany" ~ 2,
                            Country == "Greece" ~ 3,
                            Country == "Italy" ~ 3,
                            Country == "France" ~ 2,
                            Country == "Netherlands" ~ 2,
                            Country == "Sweden" ~ 2,
                            Country == "Spain" ~ 3,
                            Country == "Belgium" ~ 2,
                            Country == "UK" ~ 4,
                            Country == "U.S." ~ 4,
                            Country == "Canada" ~ 4,
                            Country == "Australia" ~ 4,
                            Country == "Malaysia" ~ 5,
                            Country == "South Korea" ~ 5,
                            Country == "Singapore" ~ 5,
                            Country == "Japan" ~ 5),
         Eco_perception = case_when(Eco_perception == "Eco_good" ~ "Good",
                                    Eco_perception == "Eco_bad" ~ "Bad")) 
```



```{r}
library(tidyverse)
library(readxl)
library(ggpubr)
library(gridExtra)
library(patchwork)
library(cowplot)
```

```{r}
dataviz <- read_xlsx("Data/proyecto.xlsx")
```


```{r}
dataviz_long <- dataviz %>% 
  pivot_longer(cols = c(2,3),
               names_to = "Eco_perception",
               values_to = "Proportion")
```


```{r fig.height=8, fig.width=3.85}

p1 <- dataviz_long %>% 
  ggplot(aes(x = fct_reorder(Country, Diff), y = Proportion, fill = Eco_perception, color = Eco_perception, group = Country, label = Proportion)) +
  geom_line(color = "gray45", size = 1.5, alpha = .2) + 
  geom_point(shape = 21, size = 2.5) +
  geom_text(vjust = 2.5, nudge_x = 0.15, size = 2.75) +
  coord_flip() +
  annotate("text", x = "Poland", y = 19, label = "Current economic", size = 2.4, vjust = -3.1, color = "#657032") +
  annotate("text", x = "Poland", y = 19, label = "situation is good", size = 2.4, vjust = -1.7, color = "#657032") +
  annotate("text", x = "Poland", y = 63, label = "Current economic", size = 2.4, vjust = -3.1, color = "#326296") +
  annotate("text", x = "Poland", y = 63, label = "situation is bad", size = 2.4, vjust = -1.7, color = "#326296") +
  expand_limits(y = c(0,100),
                x = 20) +
  scale_y_continuous(breaks = c(0,100)) +
  scale_x_discrete(name = NULL) +
  scale_fill_manual(values = c("#8cb3e6", "#d5ddad")) +
  scale_color_manual(values = c("#326296", "#657032")) +
  labs(x = NULL,
       y = NULL,
       caption = "Note: All differences shown are statistically significant. \nSource: Spring 2022 Global Attitudes Survey. Q2",
       tag = "PEW RESEARCH CENTER") +
  theme(panel.background = element_rect(fill = 'white'),
        panel.grid.major = element_line(color = "gray45", size = .2),
        panel.grid.minor = element_line(color = "gray45", size = .2),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none",
        plot.title = element_text(family = "Helvetica", size = 11.5, face = "bold", vjust = 3),  
        plot.subtitle = element_text(family = "Times", size = 10, color = "gray25", face = "italic", vjust = 3),
        axis.text = element_text(family = "Helvetica", size = 9, color = "gray30"),
        axis.ticks = element_blank(),
        plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.caption = element_text(color = "gray55", size = 7.5, face = "plain", hjust = -0.05, vjust = -3),
        plot.tag.position = c(0.175, -0.03),
        plot.tag = element_text(family = "Helvetica", size = 7.5, face = "bold", hjust = .4, vjust = 1),
        plot.margin = unit(c(.7, .25, 1, .5), "cm"))

p1 

```


```{r fig.height=8, fig.width=3.85}

p2 <- dataviz %>% 
  ggplot(aes(fct_reorder(Country, Diff), Diff, label = Diff)) +
  geom_point(alpha = 0) +
  coord_flip() + 
  annotate("rect", xmin = 0.5, xmax = 20, ymin = 15.5, ymax = 20, fill = "#efefe2") +
  geom_text(label = paste("+",dataviz$Diff), y=17.5, fontface = "bold.italic", size = 2.8) +
  ylim (15.5,20) +
  expand_limits(x = 20) +
  annotate("text", x = "Poland", y = 17.5, label = "Diff", size = 2.5, vjust = -2.5, fontface = "bold.italic") +
  theme(panel.background = element_rect(fill = 'white'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y =  element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        plot.margin = unit(c(.7, 0.25, 1, 0), "cm"))

p2 
```


```{r fig.height=8, fig.width=3.85}

p1 + p2 + 
  plot_layout(widths = c(1.7, .3)) +
  plot_annotation(title = "People who see economy negatively are \nmore likely to see a worse financial \nfuture for the next generation",
                  subtitle = "% who say that when children today in (survey country) \ngrow up, they will be worse off financially than their \nparents, among those who say their country's...",
                  theme = theme(
                    plot.title = element_text(family = "Helvetica", size = 12.5, face = "bold", vjust = -3.5),  
                    plot.subtitle = element_text(family = "Times", size = 10, color = "gray25", face = "italic", vjust = -5))) 
    
#ggsave("prueba3.jpeg", width = 10, height = 20, units = "cm")

```


```{r fig.height=8, fig.width=3.85}

p1a <- dataviz_long %>% 
  ggplot(aes(x = fct_reorder(Country, Diff), y = Proportion, fill = Eco_perception, color = Eco_perception, group = Country, label = Proportion)) +
  geom_line(color = "gray45", size = 1.5, alpha = .2) + 
  geom_point(shape = 21, size = 2.5) +
  geom_text(vjust = 2.5, nudge_x = 0.15, size = 2.75) +
  coord_flip() +
  annotate("text", x = "Poland", y = 19, label = "Current economic", size = 2.4, vjust = -3.1, color = "#025902") +
  annotate("text", x = "Poland", y = 19, label = "situation is good", size = 2.4, vjust = -1.7, color = "#025902") +
  annotate("text", x = "Poland", y = 63, label = "Current economic", size = 2.4, vjust = -3.1, color = "#AB0202") +
  annotate("text", x = "Poland", y = 63, label = "situation is bad", size = 2.4, vjust = -1.7, color = "#AB0202") +
  expand_limits(y = c(0,100),
                x = 20) +
  scale_y_continuous(breaks = c(0,100)) +
  scale_x_discrete(name = NULL) +
  scale_fill_manual(values = c("#FA8080", "#A7F3A7")) +
  scale_color_manual(values = c("#AB0202", "#025902")) +
  labs(x = NULL,
       y = NULL,
       caption = "Note: All differences shown are statistically significant. \nSource: Spring 2022 Global Attitudes Survey. Q2",
       tag = "PEW RESEARCH CENTER") +
  theme(panel.background = element_rect(fill = 'white'),
        panel.grid.major = element_line(color = "gray45", size = .2),
        panel.grid.minor = element_line(color = "gray45", size = .2),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none",
        plot.title = element_text(family = "Helvetica", size = 11.5, face = "bold", vjust = 3),  
        plot.subtitle = element_text(family = "Times", size = 10, color = "gray25", face = "italic", vjust = 3),
        axis.text = element_text(family = "Helvetica", size = 9, color = "gray30"),
        axis.ticks = element_blank(),
        plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.caption = element_text(color = "gray55", size = 7.5, face = "plain", hjust = -0.05, vjust = -3),
        plot.tag.position = c(0.175, -0.03),
        plot.tag = element_text(family = "Helvetica", size = 7.5, face = "bold", hjust = .43, vjust = 1),
        plot.margin = unit(c(.7, .25, 1, .5), "cm"))

p1a

```


```{r fig.height=8, fig.width=3.85}

p2r <- dataviz %>% 
  ggplot(aes(fct_reorder(Country, Diff), Diff, label = Diff)) +
  geom_point(alpha = 0) +
  coord_flip() + 
  #annotate("rect", xmin = 0.5, xmax = 20, ymin = 15.5, ymax = 20, fill = "#efefe2") +
  geom_text(label = paste("+",dataviz$Diff), y=17.5, fontface = "bold.italic", size = 2.8, color = "gray30") +
  ylim (13,20) +
  expand_limits(x = 20) +
  geom_hline(yintercept = 13.5, size = .3, color = "gray65") +
  annotate("text", x = "Poland", y = 17.5, label = "Diff", size = 2.5, vjust = -2.5, fontface = "bold.italic") +
  theme(panel.background = element_rect(fill = 'white'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y =  element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        plot.margin = unit(c(.7, 0.25, 1, 0), "cm"))


p2r 
```


```{r fig.height=8, fig.width=3.85}

graphr <- p1a + p2r + 
  plot_layout(widths = c(1.7, .3)) +
  plot_annotation(title = "People who see economy negatively are \nmore likely to see a worse financial \nfuture for the next generation",
                  subtitle = "% who say that when children today in (survey country) \ngrow up, they will be worse off financially than their \nparents, among those who say their country's...",
                  theme = theme(
                    plot.title = element_text(family = "Helvetica", size = 12.5, face = "bold", vjust = -3.5),  
                    plot.subtitle = element_text(family = "Times", size = 10, color = "gray25", face = "italic", vjust = -5))) 

#ggsave("prueba3a.jpeg", width = 10, height = 20, units = "cm")

graphr

```


```{r fig.height=6, fig.width=8}

alt1 <- datalong_alt %>% 
  filter(zone_2 == 1) %>% 
  ggplot(aes(x = Eco_perception, y = Proportion, group = Country, color=Country)) +
  geom_vline(xintercept = "Good", size = .2, color = "grey85") +
  geom_vline(xintercept = "Bad", size = .2, color = "grey85") +
  geom_line(size = .3) +
  geom_point(size = 2) +
  annotate("text", x = "Bad", y = 72.5, label = "HU", size = 2.5,  color = "#1d42ff") +
  annotate("text", x = "Bad", y = 65.5, label = "PL", size = 2.5,  color = "#ed009c") +
  scale_fill_manual(values = c("#1d42ff", "#ed009c")) +
  scale_color_manual(values = c("#1d42ff", "#ed009c")) +
  scale_x_discrete(expand = c(0,0.09),
                   limits = c("Good", "Bad")) +
  #expand_limits(y = c(0,100)) +
  #scale_y_continuous(limits = c(19, 70), breaks = seq(20, 70, by = 10)) +
  scale_y_continuous(limits = c(19, 90), breaks = seq(20, 90, by = 10)) +
  labs(subtitle = "Hungary and Poland",
       x = NULL,
       y = NULL,
       caption = "Note: All differences shown are statistically significant. \nSource: Spring 2022 Global Attitudes Survey. Q2",
       tag = "PEW RESEARCH CENTER") +
  theme(panel.background = element_rect(fill = 'white'),
        panel.grid.major = element_line(color = "gray70", size = .15),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none",
        plot.title = element_text(family = "Helvetica", size = 13, vjust = 5),  
        plot.subtitle = element_text(family = "Helvetica", size = 8.5, color = "gray25", vjust = 3),
        axis.title = element_text(family = "Helvetica", size = 9, color = "gray30", face = "bold"),
        axis.text = element_text(family = "Helvetica", size = 8, color = "gray30"),
        axis.ticks = element_blank(),
        #plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.caption = element_text(color = "gray 45", size = 7, face = "plain", hjust = -0.05, vjust = -4),
        plot.tag.position = c(0.175, -0.03),
        plot.tag = element_text(family = "Helvetica", size = 7, face = "bold", hjust = .37, vjust = 2),
        plot.margin = unit(c(1.5, .5, 1.5, 1), "cm"))

ggsave("prueba_alt1.jpeg", width = 15, height = 22, units = "cm")



alt2 <- datalong_alt %>% 
  filter(zone_2 == 2) %>% 
  ggplot(aes(x = Eco_perception, y = Proportion, group = Country, color=Country)) +
  geom_vline(xintercept = "Good", size = .2, color = "grey85") +
  geom_vline(xintercept = "Bad", size = .2, color = "grey85") +
  geom_line(size = .3) +
  geom_point(size = 2) +
  annotate("text", x = "Bad", y = 90, label = "FR", size = 2.5, color = "#0079b1") +
  annotate("text", x = "Bad", y = 83.5, label = "BE", size = 2.5, color = "#8a76cb") +
  annotate("text", x = "Bad", y = 78.5, label = "NL", size = 2.5, color = "#e966b0") +
  annotate("text", x = "Bad", y = 72.5, label = "DE", size = 2.5, color = "#ff706a") +
  annotate("text", x = "Bad", y = 65.5, label = "SW", size = 2.5, color = "#ffa600") +
  scale_fill_manual(values = c("#8a76cb", "#0079b1", "#ff706a", "#e966b0", "#ffa600")) +
  scale_color_manual(values = c("#8a76cb", "#0079b1", "#ff706a", "#e966b0", "#ffa600")) +
  scale_x_discrete(expand = c(0,0.09),
                   limits = c("Good", "Bad")) +
  #expand_limits(y = c(0,100)) +
  #scale_y_continuous(limits = c(40, 90), breaks = seq(40, 90, by = 10)) +
  scale_y_continuous(limits = c(19, 90), breaks = seq(20, 90, by = 10)) +
  labs(subtitle = "France, Belgium, Netherlands, Germany and \nSweden",
       x = NULL,
       y = NULL) +
  theme(panel.background = element_rect(fill = 'white'),
        panel.grid.major = element_line(color = "gray70", size = .15),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none",
        plot.title = element_text(family = "Helvetica", size = 13, vjust = 5),  
        plot.subtitle = element_text(family = "Helvetica", size = 8.5, color = "gray25", vjust = 3),
        axis.title = element_text(family = "Helvetica", size = 11, color = "gray30", face = "bold"),
        axis.text = element_text(family = "Helvetica", size = 8, color = "gray30"),
         axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        #plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.caption = element_text(color = "gray 45", size = 9, face = "plain", hjust = -0.05, vjust = -4),
        plot.tag.position = c(0.175, -0.03),
        plot.tag = element_text(family = "Helvetica", size = 9, face = "bold", hjust = .67, vjust = 1),
        plot.margin = unit(c(1.5, .5, 1.5, .5), "cm"))

ggsave("prueba_alt2.jpeg", width = 15, height = 22, units = "cm")


alt3 <- datalong_alt %>% 
  filter(zone_2 == 3) %>% 
  ggplot(aes(x = Eco_perception, y = Proportion, group = Country, color=Country)) +
  geom_vline(xintercept = "Good", size = .2, color = "grey85") +
  geom_vline(xintercept = "Bad", size = .2, color = "grey85") +
  geom_line(size = .3) +
  geom_point(size = 2) +
  annotate("text", x = "Bad", y = 73.5, label = "GR", size = 2.5, color = "#73b600") +
  annotate("text", x = "Bad", y = 85.5, label = "IT", size = 2.5, color = "#eaa200") +
  annotate("text", x = "Bad", y = 79.5, label = "ES", size = 2.5, color = "#ff5441") +
  scale_fill_manual(values = c("#73b600", "#eaa200", "#ff5441")) +
  scale_color_manual(values = c("#73b600", "#eaa200", "#ff5441")) +
  scale_x_discrete(expand = c(0,0.09),
                   limits = c("Good", "Bad")) +
  #expand_limits(y = c(0,100)) +
  scale_y_continuous(limits = c(19, 90), breaks = seq(20, 90, by = 10)) +
  labs(subtitle = "Italy, Spain and Greece",
       x = NULL,
       y = NULL) +
  theme(panel.background = element_rect(fill = 'white'),
        panel.grid.major = element_line(color = "gray70", size = .15),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none",
        plot.title = element_text(family = "Helvetica", size = 13, vjust = 5),  
        plot.subtitle = element_text(family = "Helvetica", size = 8.5, color = "gray25", vjust = 3),
        axis.title = element_text(family = "Helvetica", size = 11, color = "gray30", face = "bold"),
        axis.text = element_text(family = "Helvetica", size = 8, color = "gray30"),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        #plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.caption = element_text(color = "gray 45", size = 9, face = "plain", hjust = -0.05, vjust = -4),
        plot.tag.position = c(0.175, -0.03),
        plot.tag = element_text(family = "Helvetica", size = 9, face = "bold", hjust = .67, vjust = 1),
        plot.margin = unit(c(1.5, 1, 1.5, .5), "cm"))

#ggsave("prueba_alt3.jpeg", width = 15, height = 22, units = "cm")

graph_alt <- alt1 + alt2 + alt3 +
  plot_annotation(title = "People who see economy negatively are more likely to see a worse financial future for the \nnext generation",
                  subtitle = "% who say that when children today in (survey country) grow up, they will be worse off financially than their parents,  \namong those who say their country's economic situation is good or bad (European countries)",
                  theme = theme(
                    plot.title = element_text(family = "Helvetica", size = 11.5, face = "bold", vjust = -3.5),  
                    plot.subtitle = element_text(family = "Helvetica", size = 9.5, color = "gray25", face = "italic", vjust = -5))) 

graph_alt

```
