---
title: "Steph Curry's 3 - Points Record in Context: Off the Charts"
description: |
  In this second part I will present step by step how to reproduce the graph using
  ggplot package.
categories: "2022"
author: Nicola Ricciardi
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

## Stephen Curry's 3 - Point Record in Context: Off the Charts 

It is a graph from the Sunday Sports cover celebrating 3 - point records of Stephen Curry during the last years.
The graph has 740 lines - one for each player who was in the top 20 in 3 - point shoot made starting from 1980. The best record is established by Stephen Curry with 402 3 pointers.
The colors scale highlights a a clear difference in cumulative sum during the range of time.
For the regular season 2015 - 2016 Stephen Curry is an outlier compare with the other records.


```{r}

ff <- read.delim("C:/Users/ricci/OneDrive/Desktop/ff.txt", header=TRUE)

library(ggplot2)

#install.packages("hrbrthemes")
library(hrbrthemes)
#install.packages("GGally")
library(GGally)
#install.packages("viridis")
library(viridis)


  library(ggrepel)
  #install.packages("ggtext")
  library(ggtext)
  
  #install.packages("showtext")
  library(showtext)
library(tidyverse)
library(dplyr)
```


Here, I create a function to expand the scale color I select in *my favourite colours*. In cvi_palettes I select n = 37 according to the range time of the graph. I need to set type as "continuous".
```{fig.height=7, fig.width=6, fig.align='center}
cvi_colours = list(
  cvi_purples = c("#381532", "#4b1b42", "#5d2252", "#702963",
                  "#833074", "#953784", "#a83e95"),
  my_favourite_colours = c("#CD9B9B", "#EECFA1",  "#7CCD7C", 
                           "#00688B")
)



cvi_palettes = function(name, n, all_palettes = cvi_colours, type = c("discrete", "continuous")) {
  palette = all_palettes[[name]]
  if (missing(n)) {
    n = length(palette)
  }
  type = match.arg(type)
  out = switch(type,
               continuous = grDevices::colorRampPalette(palette)(n),
               discrete = palette[1:n]
  )
  structure(out, name = name, class = "palette")
}



scale_colour_cvi_c = function(name) {
  ggplot2::scale_colour_gradientn(colours = cvi_palettes(name = name,
                                                         type = "continuous"))
}


scale_fill_cvi_c = function(name) {
  ggplot2::scale_fill_gradientn(colours = cvi_palettes(name = name,
                                                       type = "continuous"))
}



scale_color_cvi_c = scale_colour_cvi_c



cvi_palettes("my_favourite_colours", type = "continuous", n = 37)

col = c("#CD9B9B", "#CF9F9B", "#D2A39B", "#D5A89C", "#D8AC9C", "#DAB09D", "#DDB49E", "#E0B99E", "#E3BD9F", "#E5C29F", "#E8C6A0", "#EBCAA0", "#EECFA1",
"#E4CE9D", "#DBCE9A", "#D1CE97", "#C8CE94", "#BECE91", "#B4CE8E", "#ABCD8B", "#A2CD88", "#98CD85", "#8FCD82", "#85CD7F", "#7CCD7C", "#71C47D",
"#67BC7E", "#5DB37F", "#52AB81", "#48A282", "#3E9A83", "#339284", "#298985", "#1F8187", "#147888", "#0A7089", "#00688B")

```



Here, I set the coordinates of my graph according to x - axis that represent the number of games in a regular season, and y - axis that marks how many three point shoots made by a player.

```{fig.height=7, fig.width=6, fig.align='center}
n <- ggplot(ff, xlim=c(0, 83), ylim=c(0, 420)) + 
  
  geom_segment(
    aes(
      x=0, xend=0,
      y=0, yend=0
    )
  ) + geom_segment(
    aes(
      x=0, xend=83,
      y=50, yend=50
    ), color = "grey90"
  ) + geom_segment(
    aes(
      x=10, xend=83,
      y=100, yend=100
    ), color = "grey90"
  ) + geom_segment(
    aes(
      x=27, xend=83,
      y=150, yend=150
    ), color = "grey90"
  ) + geom_segment(
    aes(
      x=37, xend=83,
      y=200, yend=200
    ), color = "grey90"
  ) + geom_segment(
    aes(
      x=46, xend=83,
      y=250, yend=250
    ), color = "grey90"
  ) + geom_segment(
    aes(
      x=55, xend=83,
      y=300, yend=300
    ), color = "grey90"
  ) + geom_segment(
    aes(
      x=65, xend=83,
      y=350, yend=350
    ), color = "grey90"
  ) + geom_segment(
    aes(
      x=75, xend=83,
      y=400, yend=400
    ), color = "grey90"
  )
```

I visualize the cumulative sum of three points shoot through geom_step, where for the x - axis there is the number of games, in the y - axis there is the cumulative sum, the group and the colour change according to ID and yearSeason.
```{fig.height=7, fig.width=6, fig.align='center}
n <- n + geom_step(aes(x = ff$N_games, y = cum_sum, group = ID, color = yearSeason), linetype = "solid",
            alpha = 1, size = 1.08)
```

Here, I visualize the x - axis representing the number of games in a season.
```{fig.height=7, fig.width=6, fig.align='center}
n <-  n + geom_segment(aes(x=0, xend=83,
                   y=0, yend=0), 
               size=1) 
```

A fixed coordinate system forces a specified ratio between the physical representation of data units on the axes. The ratio is equal to 1/3, it means that one unit on the x - axis is 1/3 of one unit on the y - axis.
```{fig.height=7, fig.width=6, fig.align='center}
n <-  n + coord_fixed(ratio=1/3)
```

Here, I visualize the title according to the original graph.
```{fig.height=7, fig.width=6, fig.align='center}
n <- n + ggtitle("Stephen Curry's 3-Point Record in Context: Off the Charts")
```
I use geom_text_repel to annotate the name of the first player for every. This is a good option to increase the visualization of the graph, in fact it is possible to highlight different players with different colours and plot arrows to increase clarity and avoid overlaps.
```{fig.height=7, fig.width=6, fig.align='center}
n <- n + geom_text_repel(data = ff%>%
              select(yearSeason,slugSeason, namePlayer, P3M, top_20, N_games, cum_sum, pp)%>%
              filter(top_20 == 1)%>%
              group_by(yearSeason, slugSeason, pp,namePlayer, P3M)%>%
              summarise(
                P3M1 = sum(cum_sum)
              )%>%
              select(-P3M1),
            aes(x = 82, y = P3M, colour = yearSeason, label=pp), 
            family = "Palatino",
            fontface = "plain",
            size = 3,
            direction = "y",
            #xlim = c(83, NA),
            hjust = "left",
            #force = 2,
           #box.padding = unit(0.5, "lines"),
            #segment.size = .7,
            #segment.alpha = .5,
            #segment.linetype = "dotted",
            #box.padding = .4,
            #segment.curvature = -0.1,
            #segment.ncp = 3,
            #segment.angle = 20
            nudge_x = 9
            #check_overlap = T
            )
```

  
Here I define the color scale I created previously. I have 37 seasons for 37 different shades. According to the visualization, it is possible observe that the cumulative sum increases over the years. The exception is Stephen Curry who is off the charts with more than 400 three points shoots made over the season.
```{fig.height=7, fig.width=6, fig.align='center}

n <- n + scale_colour_gradientn(colours = col, breaks = c(1980, 2016), labels =c("1979-80", "2015-16")) 
```

I define the labels for the x - axis and the y - axis. The first axis has a label every 10 games, while y - axis has a label every 50 three - point field goals.
```{fig.height=7, fig.width=6, fig.align='center}
n <-  n + scale_x_continuous(expand = c(0,0), 
                     breaks =c(1:82), limits = c(0,110), 
                     labels = c("1st game","", "","","","","","","",
                                "10th","","","","","","","","","",
                                "20th","","","","","","","","","",
                                "30th","","","","","","","","","",
                                "40th","","","","","","","","","",
                                "50th","","","","","","","","","",
                                "60th", "","","","","","","","","",
                                "70th", "","","","","","","","","",
                                "80th","","")
                     ) + 
  scale_y_continuous(expand = c(0,4), breaks = c(0,50, 100, 150, 200, 250,
                                300, 350, 400), labels = c("", "50", "100", "150", "200", "250", "300", "350", "400"),
                     limits = c(0,420))
```
In this part I define the legend title for the plot, customizing the legend's size.
```{fig.height=7, fig.width=6, fig.align='center}
n <- n +  guides(colour = guide_colourbar(title = substitute(paste(bold("Cumulative 
three-point field 
goals made over 
the course of a 
season"))), barwidth = 0.8, barheight = 7))
```

In this part I use some functions to modify the title, customize the background or set the position of the legend.
According to the original graph I remove the axis title and the ticks from the y - axis.
```{fig.height=7, fig.width=6, fig.align='center}
n <- n + theme(
     plot.title = element_text(size = 15, family = "serif", face = "plain", hjust = 0.8),
     plot.background = element_rect(fill = "white", colour = NA),
        panel.background = element_rect(fill = "white", colour = NA),
   panel.grid.major.x = element_blank(),
 legend.position="left",

  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  axis.ticks.length.x = unit(-.2, "cm"),
  axis.ticks.y = element_blank(),
  axis.text.y = element_text(vjust = -1)) 
```
