---
title: "Resources"
---

## Recommended Bibliography

### Basic Bibliography

- Munzner, T. (2014)
  _**Visualization analysis and design**_. CRC Press.
- Tufte, E. R. (2018)
  _**The visual display of quantitative information**_. Graphics Press.
- Wickham, H., & Sievert, C. (2016)
  _**ggplot2: Elegant graphics for data analysis**_. Springer.
  [[online]](https://ggplot2-book.org/)

### Additional Bibliography

- Cleveland, W. S. (1985)
  _**The elements of graphing data**_. Wadsworth Inc.
- Meirelles, I. (2013)
  _**Design for information**_. Rockport Publishers.
- Rahlf, T. (2019)
  _**Data Visualisation with R: 111 examples**_. Springer.
- Tufte, E. R. (2018)
  _**Envisioning information**_. Graphics Press.
- Tufte, E. R. (2019)
  _**Visual explanations: Images and quantities, evidence and narrative**_.
  Graphics Press.
- Tufte, E. R. (2019)
  _**Beautiful evidence**_. Graphics Press.
- Ware, C. (2021)
  _**Information visualization: Perception for design**_. Elsevier.
- Wilkinson, L. (2005)
  _**The grammar of graphics**_. Springer New York.

## Online Resources

### Ideas for Projects

- [Over 60 New York Times Graphs for Students to Analyze](https://www.nytimes.com/2020/06/10/learning/over-60-new-york-times-graphs-for-students-to-analyze.html): A collection of graphs, maps and charts organized by topic and graph type from three years of “What’s Going On in This Graph?”
- The [Pew Research Center](https://www.pewresearch.org/) produces lots of high-quality visualizations of social data.
- [The Economist](https://www.economist.com/) publishes very nice data-driven stories.
- The Australian [Grattan Institute](https://grattan.edu.au/) publishes reports with great visualizations, and each report is accompanied by the data used to create them.

### Miscellanea

- [ggplot2 docs](https://ggplot2.tidyverse.org/)
- [ggplot2 extensions](https://exts.ggplot2.tidyverse.org/)
- [Data visualization with ggplot2 cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf)
- [Awesome ggplot2](https://github.com/erikgahner/awesome-ggplot2)
- [The R Graph Gallery](https://r-graph-gallery.com/)
- [TidyTuesday](https://github.com/rfordatascience/tidytuesday)
- [A ggplot2 Tutorial for Beautiful Plotting in R](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/),
  by Cédric Scherer
