---
title: "Unveiling birth clinical practice in Spain: mapping the cesarian sections and birth dynamics"
description: "Exploring the nuances of maternal healthcare in Spain through an augmented map, showcasing original cesarean section rates alongside additional insights such as total births per autonomous community and cesarean rates adjusted for the average maternal age."
categories: 2023
author: "Celia Muñoz"
date: "`r Sys.Date()`"
---

```{r}
# Loading packages
library(tidyverse)
library(mapSpain)
library(readr)
library(ggplot2)
library(sf)
library(stringdist)
library(fuzzyjoin)
library(ggtext)
```


```{r}
# Adjusting locale settings
my_locale <- locale(decimal_mark = ",", grouping_mark = ".")


# Reading data
cesareas <- read_delim("tasa_cesareas.csv", 
                 skip = 10, 
                 delim = ";",
                 col_names = c("ccaa", "n_partos", "estancia_partos", "edad_partos", "n_cesareas", "edad_cesareas", "estancia_cesareas", "tasa_cesareas"),
                 locale = my_locale)

# Cleaning data and generating a new cesarea rate
cesareas <- cesareas %>% 
  na.omit() %>% 
  filter(ccaa != "Total Altas") %>% 
  mutate(tasa_cesareas = (n_cesareas / n_partos) * 100)

ccaa <- cesareas %>% 
  select(ccaa)

```
```{r}
# Loading map data
spain <- esp_get_ccaa()

# Ploting the basic map
ggplot(spain) +
  geom_sf()
```



```{r}
# Comprobamos que los nombres de las CCAA coinciden y hacemos ajustes para mejorar el join
cesareas <- cesareas %>% 
  stringdist_join(
    spain,
    by = c("ccaa" = "ine.ccaa.name"),
    method = "jaccard",
    mode = "left",
    max_dist = 0.3
  ) %>% 
  mutate(
    ine.ccaa.name = if_else(ccaa == "Rioja (La)", "Rioja, La", ine.ccaa.name)) %>% 
  select(ccaa, ine.ccaa.name, n_partos, edad_partos, tasa_cesareas, edad_cesareas) # Keeping the main variables

# Joining map data and cesarean data
cesareas_map <- spain %>% 
  left_join(
    cesareas,
    by = "ine.ccaa.name"
  )  

summary(cesareas_map)
```


```{r}
# Filling the map with cesarean rate data
map <- ggplot(cesareas_map) +
  geom_sf(aes(fill = tasa_cesareas), color = "white", linewidth = 0.2)

map
```

```{r}
# Setting the specific colors and breaks
map <- map +
  scale_fill_stepsn(
    colors = c("#5EAABB", "#478B9C", "#2f6b7d", "#184c5d", "#002c3e"),
    breaks = c(13.57, 16.83, 20.10, 23.36, 26.63, 29.89),
    limits = c(13.57, 29.89)) # Setting the limits


map
```

```{r}
# Setting the coordinates so we can have space for the legend
map <- map +
    coord_sf(xlim=c(-14, 5),
           ylim=c(35, 46)) 

map
```


```{r}
# Tunning the theme, legend
map <- map +
  theme_void() +
  theme(
    legend.position = c(0.2,0.9),
    legend.direction = "horizontal",
    legend.key.width = unit(12, "mm"),
    legend.key.height = unit(5, "mm"),
    legend.background = element_blank(),
    legend.title = element_blank(),
    panel.background = element_rect(fill = "#f5f5f5",
                                    color = NA))

map
```

```{r}
# Tunning the fonts and alignment of the legend
sysfonts::font_add_google("Open Sans", family="Open Sans")
showtext::showtext_auto()

map <- map + 
  theme(text = element_text(size = 10, 
                            color = "#6d6d6d",
                            family="Open Sans"),
        legend.text.align = c(0, 0.5, 0.5, 0.5, 0.5, 0.5))

map
```

```{r}
# Enhancement
# Obtaining the standarised cesarean rate
model <- lm(tasa_cesareas ~ edad_cesareas, data = cesareas_map)
coefs <- coef(model)

cesareas_map <- cesareas_map %>% 
  mutate(tasa_cesareas_edad = tasa_cesareas - coefs['edad_cesareas'] * (edad_cesareas - mean(edad_cesareas)))

# Lets take a look at the adjusted cesarean rate
summary(cesareas_map$tasa_cesareas_edad)
```


```{r}
#spain <- esp_get_country()
cesareas_centroid <- st_centroid(cesareas_map, of_largest_polygon = TRUE)
```

```{r}
# Visualising a bubble map
bubble_map <- ggplot() +
  geom_sf(data = spain,
          linewidth = 0.1,
          alpha = 0.5) +
  geom_sf(
    data = cesareas_centroid,
    pch = 21,
    aes(size = n_partos, 
        fill = tasa_cesareas_edad),
    stroke = 0.1) +
  coord_sf(xlim=c(-17, 3.5),
           ylim=c(34, 45))
  
bubble_map
```



```{r}
# Adjusting guides
bubble_map <- bubble_map + 
 scale_fill_stepsn(
    colors = c("#5EAABB", "#478B9C", "#2f6b7d", "#184c5d", "#002c3e"),
    guide = guide_colorsteps(title = "Cesarean section rate (%)",
                             title.position = "top")) +
  scale_size(
    breaks = c(20000, 40000),
    labels = c("20", "40"),
    range = c(1, 15),
    guide = guide_legend(title="Number of births (K)", 
                         title.position="top",
                         order=2)) # Ajusta según sea necesario +

bubble_map
```

```{r}
# A few more tweaks 
bubble_map <- bubble_map + 
  theme_void() +
  theme(
    legend.position = c(0.12,0.7),
    legend.direction = "horizontal",
    legend.key.width = unit(8, "mm"),
    legend.key.height = unit(5, "mm"),
    legend.background = element_blank(),
    legend.title=element_text(face="bold", size=8),
    legend.text=element_text(size=6))  

bubble_map
```

```{r}
# Including annotations

bubble_map <- bubble_map +
  annotate("richtext", x = -8.5, y = 44.3, 
           label = paste0(
    "<span style='color: #e75c93;'>#1 </span><b>Galicia</b> becomes a higher rate<br>
    than would be expected:
    <b>25.05%</b></span>"),
    size = 3,
    hjust = 0,
    fill = NA,
    label.color = NA) +
  annotate("richtext", x = -7.5, y = 38.5, 
           label = paste0(
    "<span style='color: #e75c93;'>#2 </span><b>Extremadura</b><br>",
    "has around 7K births per year<br>
    with the highest age-adjusted c-section rate<br>
    <b>28.93%</b></span>"),
    size = 3,
    hjust = 1,
    fill = NA,
    label.color = NA)

bubble_map
```
 
```{r}
# Adding title and subtitle
bubble_map <- bubble_map + 
  labs(title = "**Regional disparities in childbirth clinical practice**",
       subtitle = "**Number of births** and _age-adjusted caesarean rates_ across autonomous communities") +
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 14),
        plot.subtitle = element_text(hjust = 0.5,
                                     size = 9)) +
  theme(plot.title = element_markdown(),
        plot.subtitle = element_markdown())

bubble_map
```


