---
title: "Longevity graph: reproduction"
description: |
 An exploration of the factors that extend or shorten human lifespan, ranked by the strength of scientific evidence, recreated and refined from an original Information is Beautiful graphic.
categories: "2025"
author: Gaia Leuzzi
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

![Original chart. Source: Information is Beautiful (2019),  
https://informationisbeautiful.net](IIB-LiveLong-2552-Oct19-1.png){.external width=100%}

## Setup and libraries

```{r setup}
library(ggplot2)
library(forcats)
library(dplyr)
library(showtext)
library(cowplot)
library(magick)
library(grid)

font_add_google("Nunito Sans", "nunito", regular.wt = 200)
font_add_google("Nunito", "nunito_title", regular.wt = 500)
font_add_google("Nunito", "nunito_subtitle", regular.wt = 200)
showtext_auto()

my_data <- read.csv("KIB_longevity data.csv")
```

## Data preparation
```{r data}
my_data_filtered <- my_data |>
  mutate(Years = as.numeric(Years)) |>
  add_row(
    Intervention = "Married happy-go-lucky outdoors-loving sex-mad hippy party-girl in senior management with a cat",
    Years = 23,
    Science_strength = 4
  )

my_data_filtered <- my_data_filtered |>
  mutate(
    Science_strength = case_when(
      Intervention == "Be polygamous, maybe" ~ 1.2,
      Intervention == "Go to church regularly" ~ 1.4,
      Intervention == "Sit down" ~ 1.6,
      Intervention == "More Pets" ~ 1.8,
      Intervention == "Eat red meat" ~ 1.9,
      Intervention == "Be rich" ~ 2.25,
      Intervention == "Be a woman" ~ 2.4,
      Intervention == "Suffer severe mental illness" ~ 2.5,
      Intervention == "Become obese" ~ 2.6,
      Intervention == "Keep smoking" ~ 2.7,
      Intervention == "Quit" ~ 2.7,
      TRUE ~ as.numeric(Science_strength)
    )
  )

levels_vec <- c(
  "Sleep too much", "Be optimistic", "Get promoted", "Live in a city", "Live in the country",
  "Eat less food", "Have a long-lived maternal grandfather", "Hang out with women - a lot!",
  "Be conscientious ", "Have more orgasms", "With close friends", "Be polygamous, maybe",
  "Go to church regularly", "Sit down", "More Pets", "Eat red meat", "Avoid cancer",
  "Avoid heart disease", "Be alcoholic", "Get health checks ", "Get married!", "Be rich",
  "Be a woman", "Suffer severe mental illness", "Become obese", "Keep smoking", "Quit",
  "Eat healthy", "Live healthily", "Have a long-lived sibling", "Exercise more",
  "Live at high altitude",
  "Married happy-go-lucky outdoors-loving sex-mad hippy party-girl in senior management with a cat"
)

my_data_filtered <- my_data_filtered |>
  mutate(
    Intervention = factor(Intervention, levels = rev(levels_vec)),
    id = as.integer(Intervention),
    Years_Capped = if_else(Intervention == "Suffer severe mental illness", -12, Years),
    bar_offset = if_else(
      Intervention == "Married happy-go-lucky outdoors-loving sex-mad hippy party-girl in senior management with a cat",
      id - 0.8,
      id + 0.2
    )
  )

id_quit <- my_data_filtered$id[my_data_filtered$Intervention == "Keep smoking"]

my_data_filtered <- my_data_filtered |>
  mutate(
    id_adj = case_when(
      Intervention == "Married happy-go-lucky outdoors-loving sex-mad hippy party-girl in senior management with a cat" ~ id - 1.5,
      id >= id_quit ~ id - 1,
      TRUE ~ id
    ),
    bar_offset = id_adj
  )
```

## Visual geometry construction
```{r plot, fig.width=70, fig.height=65, fig.showtext=TRUE}
poly_df <- my_data_filtered |>
  rowwise() |>
  mutate(
    horiz = if_else(Years_Capped > 0, pmax(0, Years_Capped - 0.80), Years_Capped + 0.80),
    diag_end = Years_Capped,
    top = bar_offset + 0.45,
    bottom = bar_offset - 0.45,
    
    base_fill = if_else(
      Intervention == "Married happy-go-lucky outdoors-loving sex-mad hippy party-girl in senior management with a cat",
      "#6b1786",
      scales::col_numeric(
        palette = c("#E5BB39", "#ea9038", "#8ECB9A"),
        domain = range(c(1, 3))
      )(Science_strength)
    ),

    poly = list({
      if (Intervention %in% c("Have a long-lived maternal grandfather", "Have a long-lived sibling")) {
        n_fade <- 90
        split_ratio <- 0.35
        
        x_split_top <- horiz * split_ratio
        x_split_bot <- diag_end * split_ratio
        
        solid_part <- data.frame(
          x = c(0, x_split_top, x_split_bot, 0),
          y = c(top, top, bottom, bottom),
          poly_id = paste0(id_adj, "_solid"),
          fill_val = base_fill,
          alpha_val = 1
        )
        
        seq_steps <- seq(split_ratio, 1, length.out = n_fade + 1)
        x_top_edge <- seq_steps * horiz
        x_bot_edge <- seq_steps * diag_end
        alphas <- seq(1, 0.05, length.out = n_fade)
        
        xs <- c()
        ys <- c()
        alpha_vec <- c()
        ids <- c()
        
        for (i in 1:n_fade) {
           xs <- c(xs, x_top_edge[i], x_top_edge[i+1], x_bot_edge[i+1], x_bot_edge[i])
           ys <- c(ys, top, top, bottom, bottom)
           alpha_vec <- c(alpha_vec, rep(alphas[i], 4))
           ids <- c(ids, rep(paste0(id_adj, "_fade_", i), 4))
        }
        
        fade_part <- data.frame(
          x = xs, y = ys, poly_id = ids, fill_val = base_fill, alpha_val = alpha_vec
        )
        
        bind_rows(solid_part, fade_part)
        
      } else {
        data.frame(
          x = c(0, horiz, diag_end, 0),
          y = c(top, top, bottom, bottom),
          poly_id = as.character(id_adj),
          fill_val = base_fill,
          alpha_val = 1
        )
      }
    })
  ) |>
  pull(poly) |>
  bind_rows()


longevity_dt <- ggplot() +
  geom_segment(
    data = data.frame(x_val = seq(-10, 20, by = 5)),
    aes(
      x = x_val, xend = x_val,
      y = max(poly_df$y) + 1,
      yend = min(poly_df$y) - 1
    ),
    color = "#FFB777",
    linewidth = 0.5,
    alpha = 0.8
  ) +
  geom_polygon(
    data = poly_df,
    aes(x = x, y = y, group = poly_id, fill = fill_val, alpha = alpha_val),
    color = NA
  ) +
  scale_alpha_identity() +
  geom_segment(
    data = data.frame(x_val = 0),
    aes(
      x = x_val, xend = x_val,
      y = max(poly_df$y) + 1,
      yend = min(poly_df$y) - 1
    ),
    color = "gray6",
    linewidth = 0.5
  ) +
  geom_text(
    data = my_data_filtered |> 
      filter(Intervention != "Married happy-go-lucky outdoors-loving sex-mad hippy party-girl in senior management with a cat"),
    aes(
      x = if_else(Years_Capped < 0, -0.2, 0.2),
      y = bar_offset,
      label = Intervention,
      hjust = if_else(Years_Capped < 0, 1, 0)
    ),
    family = "nunito",
    size = 17,
    color = "black"
  ) +
  geom_text(
    data = my_data_filtered |> 
      filter(Intervention == "Married happy-go-lucky outdoors-loving sex-mad hippy party-girl in senior management with a cat"),
    aes(
      x = 0.2,
      y = bar_offset,
      label = Intervention,
      hjust = 0
    ),
    family = "nunito_bold",
    size = 17,
    color = "white",
    fontface = "plain"
  ) +
  scale_color_manual(values = c("TRUE" = "white", "FALSE" = "black"), guide = "none") +
  annotate(
    "text",
    x = -0.5,
    y = my_data_filtered$bar_offset[
      my_data_filtered$Intervention ==
        "Married happy-go-lucky outdoors-loving sex-mad hippy party-girl in senior management with a cat"
    ],
    label = "ULTIMATE RECIPE",
    color = "#6b1786",
    family = "nunito",
    fontface = "bold",
    hjust = 1,
    size = 17
  ) +
  scale_fill_identity() +
  scale_y_continuous(NULL, breaks = NULL, labels = NULL) +
  theme(
    text = element_text(family = "nunito"),
    legend.position = "none"
  )

longevity_dt
```

## Axis and scale design
```{r axis, fig.width=70, fig.height=65, fig.showtext=TRUE}
longevity_dt <- longevity_dt +
  scale_x_continuous(
    limits = c(-25, 23),
    breaks = seq(-10, 20, by = 5),
    minor_breaks = seq(-12, 21, by = 1),
    labels = function(x) ifelse(x == 0, expression(bold("YEARS")), as.character(x)),
    sec.axis = dup_axis()
  ) +
  geom_point(
    data = data.frame(x_val = seq(-10, 20, by = 1)) |>
      dplyr::filter(x_val %% 5 != 0),
    aes(x = x_val, y = max(poly_df$y) + 1.6),
    shape = 19,
    size = 1.7,
    color = "black",
    inherit.aes = FALSE
  ) +
  coord_cartesian(clip = "off")

tick_data <- data.frame(x_val = seq(-10, 20, by = 5))
longevity_dt <- longevity_dt +
  geom_segment(
    data = tick_data,
    aes(x = x_val, xend = x_val, 
        y = max(poly_df$y) +1.45,  
        yend = max(poly_df$y) + 1.75),
    color = "black",
    linewidth = 0.6,
    inherit.aes = FALSE
  )

longevity_dt
```

## Theme and typographic styling
```{r theme, fig.width=70, fig.height=65, fig.showtext=TRUE}
longevity_dt <- longevity_dt +
  theme(
    panel.background = element_rect(fill = "#FFFFFF", color = NA),
    plot.background = element_rect(fill = "#FFFFFF", color = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x.top = element_blank(),
    axis.title.x.bottom = element_blank(),
    axis.title.y = element_blank(),
    plot.margin = unit(c(1.7, 1, 0.05, 0.05), "cm"),
    axis.text.y = element_blank(),
    axis.ticks.x.top = element_blank(),
    axis.ticks.x.bottom = element_blank(),
    legend.position = "none",
    axis.text.x = element_text(size = 50, margin = margin(t = -160)),
    axis.text.x.top = element_text(size = 50, margin = margin(b = -150)) 
  )

longevity_dt
```

## Gender-specific icons
```{r icons, fig.width=70, fig.height=65, fig.showtext=TRUE}
male_icon <- image_read("man.png")
female_icon <- image_read("women.png")

female_icon <- image_scale(female_icon, paste0(image_info(male_icon)$width, "x", image_info(male_icon)$height, "!"))

male_grob <- rasterGrob(male_icon, interpolate = TRUE)
female_grob <- rasterGrob(female_icon, interpolate = TRUE)

gender_icons <- my_data_filtered |>
  filter(Intervention %in% c(
    "Be optimistic", "Get promoted", "Have a long-lived maternal grandfather",
    "Hang out with women - a lot!", "Have more orgasms",
    "Be polygamous, maybe", "Be a woman"
  )) |>
  mutate(
    icon_type = case_when(
      Intervention %in% c("Get promoted", "Have a long-lived maternal grandfather", 
                          "Hang out with women - a lot!", "Have more orgasms", "Be polygamous, maybe") ~ "male",
      Intervention %in% c("Be optimistic", "Be a woman") ~ "female",
      TRUE ~ "male"
    ),
    x_pos = -0.5,
    y_pos = bar_offset
  )
```


## Custom legend construction
```{r legend, fig.width=70, fig.height=65, fig.showtext=TRUE}
legend_plot <- ggplot() +
  annotate("rect", xmin = 11, xmax = 14, ymin = 39.8, ymax = 40.6, fill = "#E5BB39", color = NA) +
  annotate("text", x = 12.5, y = 40.18, label = "Suggestive", family = "nunito", size = 17, color = "black") +
  annotate("rect", xmin = 14, xmax = 16, ymin = 39.8, ymax = 40.6, fill = "#EA9038", color = NA) +
  annotate("text", x = 15, y = 40.18, label = "Good", family = "nunito", size = 17, color = "black") +
  annotate("rect", xmin = 16, xmax = 18, ymin = 39.8, ymax = 40.6, fill = "#8ECB9A", color = NA) +
  annotate("text", x = 17, y = 40.18, label = "Strong", family = "nunito", size = 17, color = "black") +
  annotate("polygon", x = c(18, 18.7, 18), y = c(39.8, 39.8, 40.6), fill = "#8ECB9A", color = NA) +
  annotate("text", x = 13.5, y = 40.915, label = "STRENGTH OF SCIENCE", family = "nunito", fontface = "bold", size = 18, color = "#444444") +
  annotate("text", x = 8.12, y = 40.18, label = "male / female specific", family = "nunito", size = 15, color = "#444444") +
  coord_cartesian(xlim = c(5, 20), ylim = c(39, 43)) +
  theme_void()

legend_plot <- legend_plot +
  annotation_custom(
    grob = female_grob,
    xmin = 10.02, xmax = 10.72,
    ymin = 39.65, ymax = 40.7999
  ) +
  annotation_custom(
    grob = male_grob,
    xmin = 10.4, xmax = 11.03,
    ymin = 39.7, ymax = 40.8
  )
```

## Annotations and explanatory notes
```{r annotations, fig.width=70, fig.height=65, fig.showtext=TRUE}
icon_size <- 1

male_positions <- gender_icons |> filter(icon_type == "male")
female_positions <- gender_icons |> filter(icon_type == "female")
both_positions <- gender_icons |> filter(icon_type == "both")

longevity_dt <- longevity_dt +
  {if(nrow(male_positions) > 0) {
    lapply(1:nrow(male_positions), function(i) {
      annotation_custom(
        grob = male_grob,
        xmin = male_positions$x_pos[i] - icon_size/2,
        xmax = male_positions$x_pos[i] + icon_size/2,
        ymin = male_positions$y_pos[i] - icon_size/2,
        ymax = male_positions$y_pos[i] + icon_size/2
      )
    })
  }} +
  {if(nrow(female_positions) > 0) {
    lapply(1:nrow(female_positions), function(i) {
      annotation_custom(
        grob = female_grob,
        xmin = female_positions$x_pos[i] - icon_size/2,
        xmax = female_positions$x_pos[i] + icon_size/2,
        ymin = female_positions$y_pos[i] - icon_size/2,
        ymax = female_positions$y_pos[i] + icon_size/2
      )
    })
  }} +
  {if(nrow(both_positions) > 0) {
    lapply(1:nrow(both_positions), function(i) {
      list(
        annotation_custom(
          grob = male_grob,
          xmin = both_positions$x_pos[i] - 0.15 - icon_size/2,
          xmax = both_positions$x_pos[i] - 0.15 + icon_size/2,
          ymin = both_positions$y_pos[i] - icon_size/2,
          ymax = both_positions$y_pos[i] + icon_size/2
        ),
        annotation_custom(
          grob = female_grob,
          xmin = both_positions$x_pos[i] + 0.15 - icon_size/2,
          xmax = both_positions$x_pos[i] + 0.15 + icon_size/2,
          ymin = both_positions$y_pos[i] - icon_size/2,
          ymax = both_positions$y_pos[i] + icon_size/2
        )
      )
    })
  }}


force_left_list <- c(
  "Hang out with women - a lot!", "Be polygamous, maybe", "Sit down", "Eat healthy",
  "Have a long-lived sibling", "Keep smoking",
  "Live at a high altitude", "Be conscientious "
)

right_exceptions <- c("Get promoted", "Have more orgasms", "Get health checks ", "Exercise more")

text_overlap_list <- c("Be optimistic", "Get health checks ", "Exercise more")

notes_df <- my_data_filtered |>
  dplyr::filter(!is.na(Note) & Note != "" & Intervention != "Suffer severe mental illness") |>
  dplyr::mutate(
    Note_Wrapped = stringr::str_wrap(Note, width = 25),
    x_note_pos = dplyr::case_when(
      Intervention == "Suffer severe mental illness" ~ -14,
      Intervention %in% force_left_list ~ -5.5,
      Intervention %in% right_exceptions ~ 10,
      TRUE ~ 15
    ),
    text_hjust = dplyr::if_else(x_note_pos < 0, 1, 0),
    x_line_start = dplyr::case_when(
      Intervention == "Be optimistic" ~ 2.7,
      Intervention == "Get health checks " ~ 3.5,
      Intervention == "Exercise more" ~ 2.9,
      Intervention == "Hang out with women - a lot!" ~ -1.0,
      Intervention == "Be polygamous, maybe" ~ -1.0,
      sign(x_note_pos) == sign(Years_Capped) ~ Years_Capped,
      TRUE ~ 0
    ),
    y_pos = bar_offset,
    note_vjust = dplyr::if_else(
      Intervention == "Hang out with women - a lot!",
      0.3,
      0.8
    )
  )

mental_note_df <- my_data_filtered |>
  dplyr::filter(Intervention == "Suffer severe mental illness") |>
  dplyr::mutate(
    y_start = bar_offset,
    y_end = bar_offset + 1.2,
    x_pos = -5.5,
    x_midpoint = -9,
    Note_Wrapped = "25 years shorter\nlife expectancy"
  )

longevity_dt <- longevity_dt +
  geom_segment(
    data = notes_df,
    aes(x = x_line_start, xend = x_note_pos, y = y_pos, yend = y_pos),
    linetype = "19", color = "black", linewidth = 0.99, inherit.aes = FALSE, lineend="round"
  ) +
  geom_text(
    data = notes_df,
    aes(
      x = x_note_pos + dplyr::if_else(x_note_pos > 0, 0.2, -0.2),
      y = y_pos,
      label = Note_Wrapped,
      hjust = text_hjust,
      vjust = note_vjust
    ),
    size = 14, color = "#666", family = "sans", lineheight = 0.95, inherit.aes = FALSE
  ) +
  geom_segment(
    data = mental_note_df,
    aes(x = x_midpoint, xend = x_midpoint, y = y_start, yend = y_end),
    linetype = "19", color = "black", linewidth = 0.99, inherit.aes = FALSE, lineend="round"
  ) +
  geom_segment(
    data = mental_note_df,
    aes(x = x_midpoint, xend = -8.7, y = y_end, yend = y_end),
    linetype = "19", color = "black", linewidth = 0.99, inherit.aes = FALSE, lineend="round"
  ) +
  geom_text(
    data = mental_note_df,
    aes(x = x_pos - 0.2, y = y_end, label = Note_Wrapped),
    hjust = 1, vjust = 0.5, size = 12, color = "#666666", family = "sans", lineheight = 0.95, inherit.aes = FALSE
  )

longevity_dt
```

##Final plot composition
```{r final, fig.width=70, fig.height=65, fig.showtext=TRUE}
final_plot <- ggdraw() +
  draw_plot(longevity_dt, x = 0, y = 0, width = 1, height = 0.85) +
  draw_plot(legend_plot, x = 0.55, y = 0.85, width = 0.4, height = 0.12) +
  draw_label(
    "Live Long",
    x = 0.3, y = 0.92,
    hjust = 0, vjust = 1,
    fontfamily = "nunito_title",
    size = 140,
    color = "#333333"
  ) +
  draw_label(
    "What really extends lifespan?",
    x = 0.3, y = 0.89,
    hjust = 0, vjust = 1,
    fontfamily = "nunito_subtitle",
    size = 85,
    color = "#333333"
  )

final_plot
```
