---
title: "Income inequality: Gini coefficient before and after
tax"
description: |
  A short description of the post.
categories: "2024"
author: David Pereiro Pol
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r}
library(tidyverse)
library(readr)
library(geomtextpath)
library(grid)
library(ggalt)
library(scales)
```

```{r}
replicate_values <- function(x) {
  j <- 0 # We initialize this variable here to verify the first
  # condition in the beginning of the for loop
  for (i in 1:length(x)) {
    if (!is.na(x[i]) & i >= j) {  # We check if there is a
      # NA and we put i >= j to continue in the point in which
      # the while loop ended
      j <- i + 1 # We change the value of j to start the while
      # loop in the following
      count <- 0 # To count the next 5 positions
      while (j <= length(x) && count < 5 && is.na(x[j])) { # To change
        #possible NA

        if (!is.na(x[j])) break # If there is not a NA break

        x[j] <- x[i] # Change the NA with the previous value

        j <- j + 1

        count <- count + 1
      }
    }
  }

  j <- length(x) + 1 # We do the same but bakwards
  for (i in length(x):1) {
    if (!is.na(x[i]) & i <= j) {
      j <- i - 1
      count <- 0
      while (j >= 1 && count < 5 && is.na(x[j])) {
        if (!is.na(x[j])) break
        x[j] <- x[i]
        j <- j - 1
        count <- count + 1
      }
    }
  }
  return(x)
}
```

```{r}
gini <- read_csv(file = "data/gini_data.csv")

gini

## Cleaning of names
gini <- gini |>
  rename(
    "pre_tax_gini" = paste("10.4.2 - Redistributive impact of",
    "fiscal policy, Gini index (%) - SI_DST_FISP - Prefiscal income"),
    "post_tax_gini" = paste("10.4.2 - Redistributive impact of",
     "fiscal policy, Gini index (%) - SI_DST_FISP - Postfiscal",
     "disposable income")
  ) |>
  janitor::clean_names()

gini

## Replication of data to simulate the original distribution of the data
gini_w_replicate <- gini |>
  group_by(entity) |>
  mutate(
    pre_tax_gini = replicate_values(pre_tax_gini),
    post_tax_gini = replicate_values(post_tax_gini)
  ) |>
  ungroup()  # We replicate onward and backwards the gini index
# as in the original graph

## Replicate the continent and drop NA

gini_tidy <- gini_w_replicate |>
  group_by(entity) |>
  fill(continent, .direction = "downup") |>
  ungroup() |>
  drop_na(post_tax_gini, pre_tax_gini)

# Gini 2020

gini_tidy_2020 <- gini_tidy |>
  filter(year == 2020)
```

```{r}
## Structure

p <- ggplot(gini_tidy_2020) +
  aes(x = pre_tax_gini, y = post_tax_gini)

p
```

```{r}
p <- p +
  scale_x_continuous(limits = c(0.2,0.749),
                            minor_breaks = NULL,
                            expand = expansion(0)) +
  scale_y_continuous(limits = c(0.2, 0.660),
                     minor_breaks = NULL,
                     expand = expansion(0))
p
```



```{r}

sysfonts::font_add_google("Playfair Display", family="playfair")
sysfonts::font_add_google("Lato", family="lato")
sysfonts::font_add_google("Open Sans", family="osans")
showtext::showtext_auto() # Since Lato is the second one it is applied
# in all texts.

p <- p + theme_minimal() +
  labs(title = paste("Income inequality: Gini coefficient",
                     "before and after tax, 2020"),
       subtitle = "Inequality is measured in terms of the
       Gini coefficient of income before taxes on the horizontal
       axis and after<br>taxes on the vertical axis",
       caption = "**Data source** : World Bank",
       tag = "OurWorldinData.org/economic-inequality | CC BY",
       x = "Before tax",
       y = "After tax") +
  theme(plot.title = element_text(face = "bold",
                                  family = "playfair",
                                  size = 26,
                                  color = "#636363"),
        plot.title.position = "plot",
        plot.subtitle = ggtext::element_markdown(size = 16,
                                                 color = "#636363",
                                                 family = "lato"),
        # Markdown is used in the case of the subtitle for separating correctly
        # into two lines the subtitle
        axis.title = element_text(size = 15,
                                  color = "#636363",
                                  family = "lato"),
        axis.text = element_text(size = 15,
                                 color = "#636363",
                                 family = "lato"),
        plot.caption = ggtext::element_markdown(size = 15,
                                                color = "#636363",
                                                hjust = 0,
                                                family = "lato"),
        plot.caption.position = "plot",
        plot.tag = ggtext::element_markdown(size = 15,
                                            color = "#636363",
                                            hjust = 1,
                                            family = "lato"
                                             ),
        plot.tag.position = c(1,0.012),
        panel.grid.major = element_line(color = "#dddddd",
                                        linetype = "dashed",
                                        linewidth = 0.3
                                        ),
        plot.margin = margin(5,2,5,2)
        )

p

```


```{r}
p <- p + # Using normal abline and annotate without changing the type of
  # coordinates was very hard and the result was not as godd as using
  # this package
  geom_abline(slope = 1, intercept = 0, 
              color = "#dddddd", 
              linetype = "dashed",
              linewidth = 0.3) +
  geom_abline(slope = 2/3, intercept = 0, 
              color = "#dddddd", 
              linetype = "dashed", 
              linewidth = 0.3) +
  geom_abline(slope = 1/2, intercept = 0, 
              color = "#dddddd",
              linetype = "dashed", 
              linewidth = 0.3) +
  geom_textabline(slope = 1, intercept = 0,
                  label = "No reduction",
                  linetype = "blank",
                  size = 4,
                  hjust = 0.83,
                  color = "#a2a2a2") +
  geom_textabline(slope = 1 / 2, intercept = 0,
                  label = "Reduce by a half",
                  linetype = "blank",
                  size = 4,
                  hjust = 0.75,
                  color = "#a2a2a2") +
  geom_textabline(slope = 2 / 3, intercept = 0,
              label = "Reduce by a third",
              linetype = "blank",
              size = 4,
              hjust = 0.81,
              color = "#a2a2a2") # Explain why I used the two of them.
# Differences with annotate and color

p


```

```{r}

con_colors <- c("#a2559c", "#00847e",
            "#4c6a9c", "#e56e5a",
            "#9a5129", "#883039")
p <- p + geom_point(aes(size = population,
                        fill = continent),
                        alpha = 0.85,
                        shape = 21)  +
  scale_fill_manual(values = con_colors) 
# Beyond 7.7 the coloring gets worse
p

``` 

```{r}
p <- p + guides(fill = guide_legend(order = 1, 
                                    theme = theme(
        legend.title = element_blank(),
        legend.key.height = unit(0.4, "cm"),
        legend.text = element_text(family = "lato",
                                   size = 14)),
        override.aes = list(shape = 15, 
                            size = 2,
                            color = con_colors
                            )),
        size = guide_legend(title = 
        "Circles sized by<br> **Population**", 
                          reverse = TRUE, # Reverse change the order of the legemds notonly of the labels
                          order = 2, # That is why we used order to correct it
                            theme = theme(
        legend.title = ggtext::element_markdown(family = "lato",
                                                size = 14,
                                                hjust = 0.5),
        legend.text = element_text(family = "lato",
                                   size = 14),
        legend.title.position = "bottom"))) + 
  theme(legend.justification = c("right", "top"),
        legend.box = "vertical",
        legend.spacing.y = unit(0.1, "cm")) +
  scale_size(breaks = c(1e08, 3e08), 
             labels = label_number(scale = 1e-6, suffix = "M"), 
             range = c(1.5, 7.6))
        
p
```

```{r}
# To put the labels
gini_labels <- gini_tidy_2020 |>
  slice_sample(prop = -0.5, by = continent) # Removes randomly
# 50% of the data of each continent
```

```{r}
p <- p +
  ggrepel::geom_text_repel(aes(label = entity,
                               color = continent),
                           size = 5,
                           segment.color = NA,
                           # To erase the
                           # segment that links the points with the
                           # label,
                           max.overlaps = 7,
                           show.legend = FALSE,
                           data = gini_labels) +
  scale_color_manual(values = con_colors)
p +
  annotation_custom(
    grob = linesGrob(),
    xmin = -Inf, xmax = Inf, ymin = 0.75, ymax = 0.75
  )
```






