---
title: "Social Media Use in 2021"
description: |
  % of adults using each social media.
categories: "2022" 
author: Álvaro Sanz 
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(fig.showtext=TRUE)
```


```{r}

library(tidyverse)
library(ggplot2)
library(lemon)
library(showtext)

```


# Introduction

## Level 2 heading example

# Getting the data

```{r}

data <- read_delim("Data/database.csv")

data <- data %>% rename(
  "Social" = `Social media`
)

filtered <- data %>% 
  group_by(Social) %>% 
  filter(Year==min(Year)|Year==max(Year))

```

### Font preparation
```{r}

font_add(family = "Franklin Gothic", regular = "FRAMD.ttf")
font_add(family = "Georgia", regular = "GEORGIAI.ttf")
font_add(family = "Franklin Gothic Demi", regular = "FRADM.ttf")
showtext_auto()

```



### Chart construction

```{r}
#CREATE COLOR SCALE
colors <- c("Youtube" = "#bf4538", "Facebook" = "#23689a", "Instagram" = "#6c9acf", "Pinterest" = "#747a46",
            "Linkedin" = "#c2c88e", "Snapchat" = "#746a7c", "Twitter" = "#d1aa42", "Whatsapp" = "#253a5c",
            "TikTok" = "#e9a03f", "Reddit" = "#92885a", "Nextdoor" = "#e28377" )
#SET ANNOTATIONS
data %>% ggplot() +
  aes(Year, Use) +
  annotate("segment", x=2012, xend = 2021, y=10, yend=10, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=20, yend=20, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=30, yend=30, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=40, yend=40, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=50, yend=50, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=60, yend=60, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=70, yend=70, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=80, yend=80, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=90, yend=90, color = "grey", linetype="dotted") +
  annotate("segment", x=2012.25, xend = 2021, y=100, yend=100, color = "grey", linetype="dotted") +
  annotate("segment", x=2012, xend = 2021, y=0, yend=0, color = "grey", alpha = 0.4) +
  geom_line(aes(group=Social, color=Social), linewidth= 1) +
  geom_point(data = filtered, aes(color=Social),
             size = 1.75, shape = 21, fill="white", stroke = 1) +
  scale_color_manual(values = colors) +
  scale_x_continuous(
    name = NULL,
    limits=c(2012, 2021.2),
    n.breaks = 10,
    labels = function(x) paste0("´", substr(x, 3, 4)),
  ) +
  scale_y_continuous(
    name = NULL,
    limits=c(0, 100),
    breaks = c(20, 40, 60, 80),
    labels = c("20" = "20", "40" = "40", "60" = "60", "80" = "80"),
    expand = c(0,0)
  ) +
  annotate("text", label="100%", x=2012, y=100, color = "grey", family="Franklin Gothic", size=3.25, hjust=1.40) +
  theme(
    axis.ticks.x.bottom = element_line(color = "lightgrey"),
    panel.grid.major.y = element_line(colour = "transparent"),
    panel.grid.minor.y = element_line(colour = "transparent"),
    panel.background = element_rect(fill = "transparent"),
    legend.position = "none",
    axis.text.x.bottom = element_text(color="grey", family = "Franklin Gothic"),
    axis.text.y.left = element_text(color="grey", family = "Franklin Gothic", hjust = 1.5),
    axis.line.x.bottom = element_line(color="transparent"),
    axis.ticks.length = unit(0, "pt"),
    axis.ticks.length.x.bottom = unit(5, "pt"),
    plot.caption = element_text(family = "Franklin Gothic", color = "grey", hjust = 0),
    plot.caption.position = "plot",
    aspect.ratio = 1/1.4,
    plot.subtitle = element_text(family = "Georgia", color = "grey", size=10, hjust = 0.02),
    plot.title = element_text(family = "Franklin Gothic", hjust = 0),
    plot.title.position = "plot",
    plot.margin = margin(t=0,
                         r=0,
                         b=12,
                         l=0)
    #plot.margin = margin(0,300,0,0, "pt")
  )  +
  annotate("text", label="YouTube", y=81, x=2021, hjust=-0.8, size=3, family = "Franklin Gothic", color = "#bf4538") +
  annotate("text", label="Facebook", y=69, x=2021, hjust=-0.73, size=3, family = "Franklin Gothic", color = "#23689a") +
  annotate("text", label="Instagram", y=46, x=2021, hjust=-0.68, size=3, family = "Franklin Gothic", color = "#6c9acf") +
  annotate("text", label="Pinterest", y=40, x=2021, hjust=-0.75, size=3, family = "Franklin Gothic", color = "#747a46") +
  annotate("text", label="LinkedIn", y=34.5, x=2021, hjust=-0.82, size=3, family = "Franklin Gothic", color = "#c2c88e") +
  annotate("text", label="Snapchat", y=29, x=2021, hjust=-0.72, size=3, family = "Franklin Gothic", color = "#746a7c") +
  annotate("text", label="Twitter", y=24.5, x=2021, hjust=-0.96, size=3, family = "Franklin Gothic", color = "#d1aa42") +
  annotate("text", label="WhatsApp", y=19, x=2021, hjust=-0.65, size=3, family = "Franklin Gothic", color = "#253a5c") +
  annotate("text", label="TikTok", y=15, x=2021, hjust=-1.03, size=3, family = "Franklin Gothic", color = "#e9a03f") +
  annotate("text", label="Reddit", y=11, x=2021, hjust=-1.05, size=3, family = "Franklin Gothic", color = "#92885a") +
  annotate("text", label="Nextdoor", y=6, x=2021, hjust=-0.75, size=3, family = "Franklin Gothic", color = "#e28377") +
  
  annotate("text", label="81", y=81, x=2021, hjust=-7, size=3, family = "Franklin Gothic", color="gray30") +
  annotate("text", label="69", y=69, x=2021, hjust=-7.6, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="40", y=46, x=2021, hjust=-7, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="31", y=40, x=2021, hjust=-7, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="28", y=34.5, x=2021, hjust=-7, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="25", y=29, x=2021, hjust=-7, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="23", y=24.5, x=2021, hjust=-7.6, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="23", y=19, x=2021, hjust=-7.6, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="21", y=15, x=2021, hjust=-7, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="18", y=11, x=2021, hjust=-7, size=3, family = "Franklin Gothic",color="gray30") +
  annotate("text", label="13", y=6, x=2021, hjust=-7.6, size=3, family = "Franklin Gothic",color="gray30") +
  
  annotate("text", label= "PEW RESEARCH CENTER", x=2012, y=0, vjust=17, hjust=0.27, family = "Franklin Gothic", size=3) +
  labs(title = paste(" Growing share of Americans say that they use Youtube;\n", 
"Facebook remains one of the most widely used online\n",
"platforms among U.S. adults"),
       subtitle = "% of U.S. adults who say they ever use ...",
       caption = paste("Note: Respondents who did not give an answer are not shown. Pre-2018 telephone poll",
       "data is not available for Youtube, Snapchat and Whatsapp; pre-2019 telephone poll data is",
       "not available for Reddit. Pre-2021 telephone poll data is not available for TikTok. Trend",
       "data is not available for Nextdoor.",
       "Source: Survey of U.S. adults conducted Jan. 25-Feb. 8, 2021.", 
       '"Social media use in 2021"',  sep="\n")) +
  coord_capped_cart(bottom = 'both') +
coord_fixed(clip = 'off')

```



Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


