---
title: "Country Convergence"
description:
  This project enables the user to recreate a specific graph in OurWorldinData on GDP per capita layer by layer. It also introduces two alternative representations resorting to the same data.
  categories: "2022"
author: Nacho Pulido Ruiz
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: TRUE
---
 On the topic of Economics and Country Convergence
 
 Our aim will be to resort to visual tools in R studio and ggplot to study the topic of country economic growth and convergence. Classical Solow-Swan models of growth predict convergence as a function of the deviation of a country from its stationary state (natural level) such that we should expect convergence between LEDC´S and MEDC´s. 
 Our point of departure will be to launch the libraries we will use and to obtain the data from the Maddison Project Database.
 
```
library(tidyverse)
library(scales)
gdp <- as.data.frame(read_delim("gdp per capita.csv", 
                                delim = ";"))
```
A prior step to develop our plot will be to clean and sort the data to prepare it for our ggplot() operations. We will filter for rows containing data for 1950 and 2016 and reshape the data to have two columns accounting for GDP per capita for each country and for each year. This enables the analyst to depict a different axis for each of the years containing observations on GDP per capita.

```
gdp <- gdp %>% 
  rename(gdp_capita = gdp_per_capita) %>% 
  select(country, year,gdp_capita, ) %>% 
  filter(year %in% c(1950,2016)) %>% 
  pivot_wider(names_from = "year", values_from = gdp_capita) %>% 
  drop_na("1950", "2016") %>% 
  rename(gdp_capita_1950 = "1950", gdp_capita_2016 = "2016")
```
It will be useful for us to categorize our countries in three groups (poor, medium and rich countries) by generating a factor column using the ifelse() command in the following way:
```
gdp <- gdp %>% 
  mutate(type = ifelse(gdp_capita_2016<6000,
                       "poor",
                       ifelse(gdp_capita_2016<40000,
                              "medium",
                              "rich")))
```
Since we will have many observations for each of the countries (especially for those with middle income), we will filter for a subset of the data by selecting a random sample of middle income countries and then binding the resulting dataframe to the original one:
```
subset <- gdp %>% 
    filter(type == "medium") %>% 
  slice(sample(1:73,35,replace = FALSE))

gdp <- gdp %>% 
    filter(type != "medium") %>% 
    rbind(subset)
```
Now we have everything we need to start depicting our graph! We will call our gdp data and pipe it into the ggplot() function, defining the aesthetics desired. The advantage of having previously pivoted our data is that now we have 2 columns which account for the desired variables to be plotted:
```
plot <- gdp %>% 
  ggplot()+
  aes(gdp_capita_1950,gdp_capita_2016)
```
Now we will add some geometry to our plot. We will choose shape 21 in order to be able to fill the points with a different color from the one we will use for the contouring of it. 
```
plot <- plot +
  geom_point(shape = 21,color = "red", size = 1.5, fill = "aquamarine3")

```
Our plot requires a lot of labels inside the graph, both for lines and for points. We will take advantage of geom_text_repel() and select some transparency to the line joining the label to the geometry. We will later work on our annotations to the diagonal lines.
 
```
plot <- plot +
geom_text_repel(aes(label = country), size = 1, segment.color = 'transparent', max.overlaps = 20, force = 0.7)
```
It is time to choose appropriately the scales of our plot. A logarithmic scale will we used for both axis and we will have to introduce the dollar symbol to account for the unit of measurement. The breaks have to be manually provided by the analyst to mimic as much as possible the original plot. 
```
plot <- plot +
   scale_x_log10(label = label_number(prefix = "$"), breaks = c(400,500,700,1000,1500,2000,3000,4000,5000,7000,10000,15000,20000,30000,40000,50000,70000))+
   
  scale_y_log10(label = label_number(prefix = "$"), breaks = c(400,500,700,1000,1500,2000,3000,4000,5000,7000,10000,15000,20000,30000,40000,70000))+
```
To stick with the original plot as much as possible, we will introduce some text in our axis and title (including a subtitle) and use a bold font for the latter.
```
plot <- plot +
  labs(x="GDP per capita in 1950",
       y = "GDP per capita in 2016",
       title = quote(bold("GDP per capita in 1950 and 2016")),
       subtitle = "GDP per capita is expressed in international -$. This means that it is adjusted for price changes over time (inflation) and for price differences between countries.
       The increase or decrease between 1959 and 2016 is shown below the country name")
```
There are many informative lines in our plot used to depict the growth rate of a country in comparison to 1950.. We will use the geom_abline() to choose the slope and intercept of each one and change the color to stick to the original plot. The RGB technique will be used to determine the color of interest and the fourth argument of this function refers to the transparency (alpha), which we will set for the diagonal lines. The intercepts with the y-axis have to be transformed by the logarithm
```
plot <- plot +
geom_abline(slope = 1,intercept = 0, color = "darkblue")+
    geom_abline(slope=1, intercept=log10(c(0.5, 2, 3, 4.4, 10, 15, 30)), linetype="dotted", color = rgb(0,0,0.5,0.3))
```
In this section we will work on the theme (appearance of the plot). Notice that each of the axis has some specific color associated with it (in accordance with the horizontal and vertical grid lines). In this case, the background lines are faded and we will resort to the RGB mixture of colors providing an alpha for each color. These kind of lines will be chosen as linetype "dotted to achieve the desired dashed effect. The aspect.ratio will be set to 1 inside the theme to ensure that the proportions of the final plot obey the ones of the original graph. 
```
plot <- plot +
theme(axis.text.x = element_text(colour = "darkorchid3", size = 4),
        axis.title.x = element_text(colour = "darkorchid3", size = 9,family = "serif"),
        axis.text.y = element_text(colour = "cyan3", size = 4,family = "serif"),
        axis.title.y = element_text(colour = "cyan3", size = 9, family = "serif"),
        plot.subtitle = element_text(size = 5, colour = rgb(0,0,0,0.6),hjust = -0.5, vjust = 5,family = "serif"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_line(color = rgb(0.6,0.196,0.8,0.4),linetype = "dotted"),
        panel.grid.major.y = element_line(color = rgb(0,1,1,0.4), linetype = "dotted"),
        plot.title = element_text(size = 14,hjust = -0.8, vjust = 1),
        aspect.ratio = 1)
```
Coordinates will be kept ass Cartesian but we will employ the use of some limits to mimic the ones from the original plot
```
plot <- plot +
coord_cartesian(xlim = c(400,70000), ylim = c(400,70000))
```
We will now work on the annotations accompanying the vertical lines which will indicate the amount of growth that each of the countries have experienced since 1950, thus, conveying the idea of convergence/divergence among them.
```
plot <- plot +
annotate("text", label = "Countries above this line had positive growth", color = "darkgreen", x = 22000, y = 25000, angle = 45, size = 2.3,family = "serif")+
    annotate("text", label = "Countries below this line had negative growth", color = "red", x = 26000, y = 23000, angle = 45, size = 2.3,family = "serif")
```
Graph enhancement: 

We will use the same graph to propose some enhancements or changes in the way the data is presented in an attempt to ease reader´s comprehension. We will reload the data to our Rstudio code:
```
gdp <- as.data.frame(read_delim("gdp per capita.csv", 
                                  delim = ";"))
```
The same technique employed before to clean and prepare our data will be recycled. Recall we are just proposing an improvement of the visualisation, an alternative graph will be proposed in the last section of the project. Once again, we categorise our countries into rich, medium and poor:
``` 
gdp <- gdp %>% 
    rename(gdp_capita = gdp_per_capita) %>% 
    select(country, year,gdp_capita, ) %>% 
    filter(year %in% c(1950,2016)) %>% 
    pivot_wider(names_from = "year", values_from = gdp_capita) %>% 
    drop_na("1950", "2016") %>% 
    rename(gdp_capita_1950 = "1950", gdp_capita_2016 = "2016") %>% 
    mutate(type = ifelse(gdp_capita_2016<6000,
                         "poor",
                         ifelse(gdp_capita_2016<40000,
                                "medium",
                                "rich")))
```                               
The main difference with the first plot is that, this time, we will resort to the inclusion of a new column which will summarise the average annual growth rate that each economy has undergone since 1950.
``` 
gdp <- gdp %>% 
 mutate(Growth = (((gdp_capita_2016/gdp_capita_1950)^(1/(2016-1950)))-1)*100)
``` 
As we mentioned previously, the plot will be the same but we will just change the way the data is presented, so the random filter to select countries will be preserved:

```
subset <- gdp %>% 
    filter(type == "medium") %>% 
    slice(sample(1:73,35,replace = FALSE))
  gdp <- gdp %>% 
    filter(type != "medium") %>% 
    rbind(subset)
```
We can begin with our enhanced graph! The aesthetics provided now will be set to the gdp per capita in 1950 and the annual growth rate we computed before. We will make use of our geom_label() again but we will omit supplying R with geom_point() this time. The color of the text will be set to white in order to generate a comfortable contrast with the "filling" by type of economy we had established in our aesthetics. 
```
plot_1 <-gdp %>% 
    ggplot()+
    aes(gdp_capita_1950,Growth, fill = type)+
    geom_label_repel(aes(label = country), size = 1.5, segment.color = 'transparent', max.overlaps = 25, force = 1, color = "white")
```
We will add some labels to our axis and set the title to convey the idea that we are working with convergence. The word "conditional" here refers to the fact that we are going one step further and categorizing our data between types of economies and we will finally visualize the concept of "conditional convergence" presented in the classical Solow model of growth.
```
plot_1 <- plot_1 +
labs(x="GDP per capita in 1950",
         y = "Average GDP Growth Rate",
         title = quote(bold("GDP per capita conditional convergence")))
```
We will provide a continuous y scale with the percentage suffix to make it obvious that we are working with growth rates here.
``` 
plot_1 +
scale_y_continuous(label = label_number(suffix = "%"), n.breaks = 6)
``` 
We will work on the themes by providing some font in the type of "serif" and eliminating any background grid which may distract the reader. We will not devote much effort into changing the theme appearance because we are just modifying some changes of the original plot, not changing the graph completely. The aspect ratio will be set again to 1 to keep the original proportions. 

``` 
theme(axis.text.x = element_text( size = 7),
          axis.title.x = element_text( size = 12,family = "serif"),
          axis.text.y = element_text(size = 7,family = "serif"),
          axis.title.y = element_text( size = 12, family = "serif"),
          panel.background = element_rect(fill = "white"),
          panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_blank(),
          plot.title = element_text(size = 15,hjust = -0.8, vjust = 1),
          aspect.ratio = 1)
```          
