---
title: "SHOWING THE RACE OR ORIGIN PERCENTAGES OF EACH STATE"
description: |
  Replicating spiral charts and exploring alternative designs for clarity.
author: Gaspar Vigneaux
date: 2025-11-24
output:
  distill::distill_article:
    self_contained: false
    toc: true
---



REPLICATION

```{r}
# Final Project 2

library(ggplot2)
library(patchwork)
library(dplyr)
library(tidyr)
library(ggtext)
library(lubridate)
library(cowplot)

# data_main <- read.csv(file = "../Option_2/psam_pusa.csv")
#
# data_main <- data_main |>
#   select(ST, ANC1P, ANC2P, RAC1P, RAC2P, RAC3P, RACAIAN, RACASN, RACBLK, RACNH, RACNUM, RACPI, RACSOR, RACWHT, HISP)
#
#
# data_main <- data_main |>
#   rename(
#     state                = ST,
#     ancestry_primary     = ANC1P,
#     ancestry_secondary   = ANC2P,
#     race         = RAC1P,
#     race_recoded_1       = RAC2P,
#     race_recoded_2       = RAC3P,
#     race_aian            = RACAIAN,   # American Indian & Alaska Native
#     race_asian           = RACASN,
#     race_black           = RACBLK,
#     race_native_hawaiian = RACNH,
#     race_total_groups    = RACNUM,
#     race_pacific_islander= RACPI,
#     race_other           = RACSOR,
#     race_white           = RACWHT,
#     hispanic = HISP
#   )
#
# write.csv(data_main, file = "../Option_2/data_main.csv")

# data_main2 <- read.csv(file = "../Option_2/psam_pusb.csv")
# 
# data_main2 <- data_main2 |>
#   select(ST, ANC1P, ANC2P, RAC1P, RAC2P, RAC3P, RACAIAN, RACASN, RACBLK, RACNH, RACNUM, RACPI, RACSOR, RACWHT, HISP)
# 
# 
# data_main2 <- data_main2 |>
#   rename(
#     state                = ST,
#     ancestry_primary     = ANC1P,
#     ancestry_secondary   = ANC2P,
#     race         = RAC1P,
#     race_recoded_1       = RAC2P,
#     race_recoded_2       = RAC3P,
#     race_aian            = RACAIAN,   # American Indian & Alaska Native
#     race_asian           = RACASN,
#     race_black           = RACBLK,
#     race_native_hawaiian = RACNH,
#     race_total_groups    = RACNUM,
#     race_pacific_islander= RACPI,
#     race_other           = RACSOR,
#     race_white           = RACWHT,
#     hispanic = HISP
#   )
# 
# write.csv(data_main2, file = "../Option_2/data_main2.csv")

data_main <- read.csv(file = "../100458045/data_main.csv")
data_main2 <- read.csv(file = "../100458045/data_main2.csv")

data_main_completo <- bind_rows(data_main, data_main2)

set.seed(40)
data_sample <- data_main_completo |> 
  sample_frac(1)

# Spiral Packages 

# library(spiralize)
# 
# Graph <- ggplot(data_main) 
# 
# 
# spiral_initialize(...)
# spiral_track(...)
# spiral_points(...)

# Recoding race 

data_sample <- data_sample |> 
  mutate(
    race_final = case_when(
      hispanic != 1 ~ 2, #hispanic
      race == 1 ~ 1,              # White
      race == 2 ~ 3,              # Black / African American
      race == 6 ~ 4,              # Asian
      race %in% c(3, 4, 5) ~ 5,   # American Indian / Alaska Native
      race == 7 ~ 6,              # Native Hawaiian & Pacific Islander
      .default = NA_real_
    ), race_final = factor(
      race_final,
      levels = c(1, 2, 3, 4, 5, 6),
      labels = c(
        "WHITE",
        "HISPANIC OR LATINO",
        "BLACK OR AFRICAN AMERICAN",
        "ASIAN",
        "AMERICAN INDIAN AND ALASKA NATIVE",
        "NATIVE HAWAIIAN AND PACIFIC ISLANDER"
      )
    )
  )

data_sample <- data_sample |> 
  filter(!is.na(race_final) & !is.na(race_total_groups) & race_total_groups < 2)

# State variable  

data_main_completo |> 
  count(state)

data_sample <- data_sample |> 
  filter(state %in% c(1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 
                      20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 
                      34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 
                      49, 50, 51, 53, 54, 55, 56))

data_sample |> 
  count(state)

state_names <- c(
  "0" = "United States",
  "1" = "Alabama", "2" = "Alaska", "4" = "Arizona", "5" = "Arkansas",
  "6" = "California", "8" = "Colorado", "9" = "Connecticut", "10" = "Delaware",
  "11" = "District of Columbia", "12" = "Florida", "13" = "Georgia",
  "15" = "Hawaii", "16" = "Idaho", "17" = "Illinois", "18" = "Indiana",
  "19" = "Iowa", "20" = "Kansas", "21" = "Kentucky", "22" = "Louisiana",
  "23" = "Maine", "24" = "Maryland", "25" = "Massachusetts", "26" = "Michigan",
  "27" = "Minnesota", "28" = "Mississippi", "29" = "Missouri", "30" = "Montana",
  "31" = "Nebraska", "32" = "Nevada", "33" = "New Hampshire", "34" = "New Jersey",
  "35" = "New Mexico", "36" = "New York", "37" = "North Carolina", "38" = "North Dakota",
  "39" = "Ohio", "40" = "Oklahoma", "41" = "Oregon", "42" = "Pennsylvania",
  "44" = "Rhode Island", "45" = "South Carolina", "46" = "South Dakota",
  "47" = "Tennessee", "48" = "Texas", "49" = "Utah", "50" = "Vermont",
  "51" = "Virginia", "53" = "Washington", "54" = "West Virginia",
  "55" = "Wisconsin", "56" = "Wyoming"
)

# Proportions 

race_prop <- data_sample |> 
  group_by(race_final) |> 
  summarise(count = n()) |> 
  mutate(prop = count / sum(count)) |> 
  mutate(cum_prop = cumsum(prop), 
         start = lag(cum_prop, default = 0))

geom_col_race <- ggplot(race_prop) + 
  aes(x = race_final, y = prop) +
  geom_col()
geom_col_race

# Spiral data frame 

a <- 5
b <- 1
theta <- seq(0, 24*pi, 0.01)
theta <- rev(theta)
r <- a + b*theta
spiral <- data.frame(x = r*cos(theta), y = r*sin(theta))

## graph trial
max_r <- max(r)

spiral_graph <- ggplot(spiral, aes(x, y)) +
  geom_point(col = '#eac964', size = 1) +
  coord_fixed(xlim = c(-max_r, max_r), ylim = c(-max_r, max_r))

spiral_graph

# How to fit my data in the spiral 

spiral_applied_df <- spiral |> 
  mutate(
    position = row_number()/n(),
    race_final = cut(position, 
                     breaks = c(race_prop$start, 1), 
                     labels =  race_prop$race_final, 
                     include.lowest = TRUE)
  )

max_r <- max(r)

spiral_graph_applied <- ggplot(spiral_applied_df, 
                               aes(x, y, color = race_final)) + 
  geom_point(size =1.5) +
  coord_fixed(xlim = c(-max_r, max_r), ylim = c(-max_r, max_r)) 

spiral_graph_applied


race_colors <- c(
  "WHITE" = "#ddc56c",  # White
  "HISPANIC OR LATINO" = "#62743c",  # Hispanic/Latino
  "BLACK OR AFRICAN AMERICAN" = "#515da1",  # Black/African American
  "ASIAN" = "#833e3d",  # Asian
  "AMERICAN INDIAN AND ALASKA NATIVE" = "#7b5a8e",  # American Indian/Alaska Native
  "NATIVE HAWAIIAN AND PACIFIC ISLANDER" = "#dd824a"   # Native Hawaiian & Pacific Islander
)

spiral_graph_applied <- spiral_graph_applied +
  scale_color_manual(values = race_colors) 

spiral_graph_applied <- spiral_graph_applied +
  geom_path(linewidth = 1)

spiral

spiral_graph_applied

# FACET WRAP 

race_prop_usa <- data_sample |> 
  group_by(race_final) |> 
  summarise(count = n(), .groups = "drop") |> 
  mutate(
    prop = count / sum(count),
    cum_prop = cumsum(prop), 
    start = lag(cum_prop, default = 0),
    state = 0  
  )

race_prop_by_state <- data_sample |> 
  group_by(state, race_final) |> 
  summarise(count = n(), .groups = "drop") |> 
  group_by(state) |> 
  mutate(
    prop = count / sum(count),
    cum_prop = cumsum(prop), 
    start = lag(cum_prop, default = 0)
  )

race_prop_completo <- bind_rows(race_prop_usa, race_prop_by_state)

spiral_all_states <- race_prop_completo |> 
  group_by(state) |> 
  reframe(
    spiral |> 
      mutate(
        position = row_number()/n(),
        race_final = cut(
          position, 
          breaks = c(start, 1), 
          labels = race_final, 
          include.lowest = TRUE
        )
      )
  ) |>
  mutate(state_name = state_names[as.character(state)])

spiral_all_states <- spiral_all_states |>
  mutate(state_name = factor(state_name, 
                             levels = c("United States", 
                                        sort(setdiff(unique(state_name), "United States")))))

spiral_graph_multi <- ggplot(spiral_all_states, aes(x, y, color = race_final)) + 
  geom_point(size = 0.5) +
  scale_color_manual(values = race_colors) +
  coord_fixed() +
  facet_wrap(~state_name, ncol = 8, nrow = 7)


spiral_graph_multi




# 1. Main graph


main_plot <- spiral_graph_multi +
  geom_path(aes(group = state_name), linewidth = 0.35, alpha = 0.9) +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.background = element_rect(fill = "grey90", color = NA),
    panel.background = element_rect(fill = "grey90", color = NA),
    strip.text = element_text(
      size = 8, 
      family = "serif", 
      face = "plain", 
      margin = margin(b = 3, t = 2)
    ),
    legend.position = "none",
    panel.spacing = unit(0.4, "lines"),
    plot.margin = margin(5, 5, 5, 5)
  )

# 2. Legends

legend_plot <- spiral_graph_multi +
  theme_minimal() +
  theme(
    legend.position = "right",
    legend.title = element_blank(),
    legend.text = element_text(
      size = 8, 
      family = "serif", 
      lineheight = 1.2
    ),
    legend.key.size = unit(0.35, "cm"),
    legend.spacing.y = unit(0.2, "cm"),
    legend.background = element_rect(fill = "grey90", color = NA),
    plot.background = element_rect(fill = "grey90", color = NA),
    legend.box.background = element_rect(fill = "grey90", color = NA)
  ) +
  guides(color = guide_legend(
    override.aes = list(
      size = 3.5,
      shape = 16,
      alpha = 1
    )
  ))

legend <- get_legend(legend_plot)

# 3. Title

title_plot <- ggplot() +
  theme_void() +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
  theme(
    plot.background = element_rect(fill = "grey90", color = NA),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  annotate(
    "text",
    x = 0.5, y = 0.70,
    label = "CHARTS",
    family = "serif",
    fontface = "bold",
    size = 6,
    hjust = 0.5,
    vjust = 1
  ) +
  annotate(
    "text",
    x = 0.5, y = 0.50,
    label = "SHOWING THE",
    family = "serif",
    fontface = "plain",
    size = 6,
    hjust = 0.5,
    vjust = 1
  ) +
  annotate(
    "text",
    x = 0.5, y = 0.30,
    label = "RACE OR ORIGIN",
    family = "serif",
    fontface = "bold",
    size = 6,
    hjust = 0.5,
    vjust = 1
  ) +
  annotate(
    "text",
    x = 0.5, y = 0.10,
    label = "PERCENTAGES OF EACH STATE",
    family = "serif",
    fontface = "plain",
    size = 6,
    hjust = 0.5,
    vjust = 1
  )


# 4. Subtitle


subtitle_plot <- ggplot() +
  theme_void() +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
  theme(
    plot.background = element_rect(fill = "grey90", color = NA),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  annotate(
    "text", 
    x = 0.5, y = 0.5,
    label = "Compiled using estimates from the American Community Survey 2018", 
    family = "serif",
    fontface = "italic",
    size = 2.8,
    hjust = 0.5,
    vjust = 0.5
  )
# 5. Explanation


explanation_plot <- ggplot() +
  theme_void() +
  theme(plot.background = element_rect(fill = "grey90", color = NA), plot.margin = margin(5, 5, 5, 5)) +
  coord_cartesian(xlim = c(-0.2, 1.2), ylim = c(0, 1), clip = "off") +  
  annotate(
    "text", 
    x = -0.15, y = 0.5,    
    label = "EXPLANATION. Each spiral represents the\npercentage of those who identify with the race\nor origin listed. Segment length is proportional\nto the percentage of each group, as it relates to\nthe full length of the spiral.",
    family = "serif", 
    size = 3.2,
    hjust = 0,
    vjust = 0.5,
    lineheight = 1.1
  )


# 6. Note

note_text <- "NOTE. Survey respondents are allowed to answer more than\none race and can have Hispanic or Latino origin or not. For\nthe sake of simplicity, the percentages shown for each race\nare for those who only selected a single race and are non-\nHispanic. Hispanic or Latino is then shown separately for\ncomparison."


# 7. Layout



top_row <- explanation_plot + title_plot + wrap_elements(full = legend) + 
  plot_layout(widths = c(2, 4, 2)) +
  plot_annotation(theme = theme(
    plot.background = element_rect(fill = "grey90", color = NA),
    plot.margin = margin(0, 0, 0, 0)
  ))

second_row <- plot_spacer() + subtitle_plot + plot_spacer() +
  plot_layout(widths = c(2, 4, 2)) +
  plot_annotation(theme = theme(
    plot.background = element_rect(fill = "grey90", color = NA),
    plot.margin = margin(0, 0, 0, 0)
  ))


final_plot <- top_row / second_row / main_plot +
  plot_layout(heights = c(0.10, 0.02, 1)) +
  plot_annotation(
    caption = note_text, 
    theme = theme(
      plot.caption = element_text(
        family = "serif", 
        size = 7.5, 
        hjust = 0.8,
        vjust = 0,
        lineheight = 1.1, 
        margin = margin(t = -30, r = 50, b = 5, l = 0)
      ),
      plot.background = element_rect(fill = "grey90", color = NA),
      plot.margin = margin(10, 10, 10, 10)
    )
  )


# 8. Saving


# PDF Vertical
ggsave(
  "spiral_trial.pdf", 
  final_plot,
  width = 11,      
  height = 14,     
  device = "pdf",
  bg = "grey90"
)

# PNG Vertical  
ggsave(
  "spiral_trial.png",        
  final_plot,                      
  width = 11,                      
  height = 14,                     
  dpi = 600,                       
  bg = "grey90"
)
```

CLEANING ENVIROMENT
```{r}
rm(list = ls())
```


IMPROVEMENT

```{r}

library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(viridis)



data_main <- read.csv(file = "../100458045/data_main.csv")
data_main2 <- read.csv(file = "../100458045/data_main2.csv")

data_main_completo <- bind_rows(data_main, data_main2)

set.seed(40)
data_sample <- data_main_completo |> 
  sample_frac(1)


data_sample <- data_sample |> 
  mutate(
    race_final = case_when(
      hispanic != 1 ~ 2, 
      race == 1 ~ 1,              
      race == 2 ~ 3,              
      race == 6 ~ 4,              
      race %in% c(3, 4, 5) ~ 5,   
      race == 7 ~ 6,              
      .default = NA_real_
    ), race_final = factor(
      race_final,
      levels = c(1, 2, 3, 4, 5, 6),
      labels = c(
        "WHITE",
        "HISPANIC OR LATINO",
        "BLACK OR AFRICAN AMERICAN",
        "ASIAN",
        "AMERICAN INDIAN AND ALASKA NATIVE",
        "NATIVE HAWAIIAN AND PACIFIC ISLANDER"
      )
    )
  )

data_sample <- data_sample |> 
  filter(!is.na(race_final) & !is.na(race_total_groups) & race_total_groups < 2)

race_colors <- c(
  "WHITE" = "#ddc56c",  # White
  "HISPANIC OR LATINO" = "#62743c",  # Hispanic/Latino
  "BLACK OR AFRICAN AMERICAN" = "#515da1",  # Black/African American
  "ASIAN" = "#833e3d",  # Asian
  "AMERICAN INDIAN AND ALASKA NATIVE" = "#7b5a8e",  # American Indian/Alaska Native
  "NATIVE HAWAIIAN AND PACIFIC ISLANDER" = "#dd824a"   # Native Hawaiian & Pacific Islander
)


data_main_completo |> 
  count(state)

data_sample <- data_sample |> 
  filter(state %in% c(1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 
                      20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 
                      34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 
                      49, 50, 51, 53, 54, 55, 56))

data_sample |> 
  count(state)

state_names <- c(
  "0" = "United States",
  "1" = "Alabama", "2" = "Alaska", "4" = "Arizona", "5" = "Arkansas",
  "6" = "California", "8" = "Colorado", "9" = "Connecticut", "10" = "Delaware",
  "11" = "District of Columbia", "12" = "Florida", "13" = "Georgia",
  "15" = "Hawaii", "16" = "Idaho", "17" = "Illinois", "18" = "Indiana",
  "19" = "Iowa", "20" = "Kansas", "21" = "Kentucky", "22" = "Louisiana",
  "23" = "Maine", "24" = "Maryland", "25" = "Massachusetts", "26" = "Michigan",
  "27" = "Minnesota", "28" = "Mississippi", "29" = "Missouri", "30" = "Montana",
  "31" = "Nebraska", "32" = "Nevada", "33" = "New Hampshire", "34" = "New Jersey",
  "35" = "New Mexico", "36" = "New York", "37" = "North Carolina", "38" = "North Dakota",
  "39" = "Ohio", "40" = "Oklahoma", "41" = "Oregon", "42" = "Pennsylvania",
  "44" = "Rhode Island", "45" = "South Carolina", "46" = "South Dakota",
  "47" = "Tennessee", "48" = "Texas", "49" = "Utah", "50" = "Vermont",
  "51" = "Virginia", "53" = "Washington", "54" = "West Virginia",
  "55" = "Wisconsin", "56" = "Wyoming"
)

race_by_state <- data_sample |>
  group_by(state, race_final) |>
  summarise(count = n(), .groups = "drop") |>
  group_by(state) |>
  mutate(
    total = sum(count),
    percentage = (count / total) * 100
  ) |>
  ungroup() |>
  mutate(state_name = state_names[as.character(state)])




empty_bar <- 1
state_list <- unique(race_by_state$state_name)
n_states <- length(state_list)

main_data <- race_by_state |>
  arrange(state_name, race_final) |>
  group_by(state_name) |>
  mutate(id = cur_group_id()) |>
  ungroup()

label_data_main <- main_data |>
  group_by(state_name, id) |>
  summarise(total = sum(percentage), .groups = "drop") |>
  mutate(
    angle = 90 - 360 * (id - 0.5) / n_states,
    hjust = ifelse(angle < -90, 1, 0),
    angle = ifelse(angle < -90, angle + 180, angle)
  )

main_circular <- ggplot(main_data, aes(x = as.factor(id), y = percentage, fill = race_final)) +
  geom_bar(stat = "identity", alpha = 0.85, color = "white", linewidth = 0.3) +
  scale_fill_manual(values = race_colors) +
  geom_segment(aes(x = 0, y = 25, xend = n_states, yend = 25), 
               colour = "grey80", alpha = 0.5, linewidth = 0.3) +
  geom_segment(aes(x = 0, y = 50, xend = n_states, yend = 50), 
               colour = "grey80", alpha = 0.5, linewidth = 0.3) +
  geom_segment(aes(x = 0, y = 75, xend = n_states, yend = 75), 
               colour = "grey80", alpha = 0.5, linewidth = 0.3) +
  geom_segment(aes(x = 0, y = 100, xend = n_states, yend = 100), 
               colour = "grey80", alpha = 0.5, linewidth = 0.3) +
    annotate("text", x = 0, y = c(25, 50, 75, 100), 
           label = c("25%", "50%", "75%", "100%"),
           color = "grey40", size = 3.5, fontface = "bold") +
    geom_text(data = label_data_main, 
            aes(x = id, y = total + 8, label = state_name, 
                angle = angle, hjust = hjust),
            color = "black", size = 3, fontface = "bold", 
            inherit.aes = FALSE) +
  ylim(-30, 120) +
  coord_polar(start = 0) +
  theme_minimal() +
  theme(
    legend.position = c(1, 0),  
    legend.justification = c(1, 0),   
    legend.title = element_blank(),
    legend.text = element_text(size = 6, family = "serif"),
    legend.key.size = unit(0.3, "cm"),
    legend.background = element_rect(fill = "white", color = "grey80", linewidth = 0.3),
    legend.margin = margin(3, 3, 3, 3),
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(size = 16, hjust = 0.5, face = "bold", family = "serif"),
    plot.margin = margin(10, 10, 10, 10)
  ) +
  guides(fill = guide_legend(ncol = 1)) +  
  labs(title = "CHARTS SHOWING THE RACE OR ORIGIN PERCENTAGES OF EACH STATE")



create_category_plot <- function(category_name, color) {
    category_data <- race_by_state |>
    filter(race_final == category_name) |>
    arrange(desc(percentage)) |>  
    mutate(id = row_number())
  
  n_bars <- nrow(category_data)
  

  label_data <- category_data |>
    mutate(
      angle = 90 - 360 * (id - 0.5) / n_bars,
      hjust = ifelse(angle < -90, 1, 0),
      angle = ifelse(angle < -90, angle + 180, angle)
    )
  
  p <- ggplot(category_data, aes(x = as.factor(id), y = percentage)) +
    geom_bar(stat = "identity", fill = color, alpha = 0.85, 
             color = "white", linewidth = 0.3) +
    
    geom_segment(aes(x = 0, y = 25, xend = n_bars, yend = 25), 
                 colour = "grey80", alpha = 0.5, linewidth = 0.2) +
    geom_segment(aes(x = 0, y = 50, xend = n_bars, yend = 50), 
                 colour = "grey80", alpha = 0.5, linewidth = 0.2) +
    geom_segment(aes(x = 0, y = 75, xend = n_bars, yend = 75), 
                 colour = "grey80", alpha = 0.5, linewidth = 0.2) +
    
    annotate("text", x = 0, y = c(25, 50, 75), 
             label = c("25%", "50%", "75%"),
             color = "grey40", size = 1.5) +
    
    geom_text(data = label_data, 
              aes(x = id, y = percentage + 5, label = state_name, 
                  angle = angle, hjust = hjust),
              color = "black", size = 1.5, inherit.aes = FALSE) +
    
    ylim(-20, 90) +
    coord_polar(start = 0) +
    theme_minimal() +
    theme(
      legend.position = "none",
      axis.text = element_blank(),
      axis.title = element_blank(),
      panel.grid = element_blank(),
      plot.title = element_text(size = 10, hjust = 0.5, face = "bold", family = "serif"),
      plot.margin = margin(5, 5, 5, 5)
    ) +
    labs(title = category_name)
  
  return(p)
}

categories <- levels(data_sample$race_final)

white_plot <- create_category_plot("WHITE", race_colors["WHITE"])
hispanic_plot <- create_category_plot("HISPANIC OR LATINO", race_colors["HISPANIC OR LATINO"])
black_plot <- create_category_plot("BLACK OR AFRICAN AMERICAN", race_colors["BLACK OR AFRICAN AMERICAN"])
asian_plot <- create_category_plot("ASIAN", race_colors["ASIAN"])
native_plot <- create_category_plot("AMERICAN INDIAN AND ALASKA NATIVE", race_colors["AMERICAN INDIAN AND ALASKA NATIVE"])
pacific_plot <- create_category_plot("NATIVE HAWAIIAN AND PACIFIC ISLANDER", race_colors["NATIVE HAWAIIAN AND PACIFIC ISLANDER"])



# Combining main graph with zoomed graphs

detail_grid <- (white_plot + hispanic_plot) / 
  (black_plot + asian_plot) /
  (native_plot + pacific_plot) +
  plot_layout(heights = c(1, 1, 1))

final_layout_sidebyside <- main_circular | detail_grid +
  plot_layout(widths = c(1, 4)) +  
  plot_annotation(
    title = "CHARTS SHOWING THE RACE OR ORIGIN PERCENTAGES OF EACH STATE",
    subtitle = "Left: Overall composition by state | Right: Distribution of each category (ordered by percentage)",
    theme = theme(
      plot.title = element_text(size = 18, hjust = 0.5, face = "bold", family = "serif"),
      plot.subtitle = element_text(size = 11, hjust = 0.5, family = "serif", margin = margin(b = 10))
    )
  )





ggsave(
  "improvement_trial.png",
  final_layout_sidebyside,
  width = 20,
  height = 12,
  dpi = 600,
  bg = "white"
)

ggsave(
  "improvement_trial.pdf",
  final_layout_sidebyside,
  width = 20,
  height = 12,
  device = "pdf",
  bg = "white"
)


```
