---
title: "American's top concerns. 2022."
description: |
  Most important issues for american's, April-October 2022.
author: Mireia Hontanares Belda Cortés
date: 2023-12-18
output:
  distill::distill_article:
    self_contained: false
---





```{r}
library(alluvial)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggalluvial)
library(ggtext)
library(extrafont)
library(geomtextpath)
library(ggannotate)
library(shadowtext)
library(readxl)

# datos
df  <- read_excel("C:/Users/Concha Cortés/Desktop/Máster/Cuatrimestre 1/Data visualization/potser.xlsx")

# Filtrado "None of these" y "Other"

datos_filtrados <- df %>%
  filter(Categoría != "None of these" & Categoría != "Other")

# Recodificación de nombres

datos_filtrados$Waves <- recode(datos_filtrados$Waves,
                                "W1" = "WAVE 1",
                                "W2" = "WAVE 2",
                                "W3" = "WAVE 3",
                                "W4" = "WAVE 4",
                                "W5" = "WAVE 5",
                                "W6" = "WAVE 6")

datos_filtrados$Categoría <- recode(datos_filtrados$Categoría,
                                    "Inflation or increasing costs" = "Inflation",
                                    "Political extremism or polarization"= "Political extremism",
                                    "Government budget and debt" = "Government budget/debt",
                                    "Election security or fraud" = "Election security",
                                    "Opioid or drug addiction" = "Drug addiction",
                                    "COVID-19/ coronavirus" = "COVID-19") 


# ordenar categorías
orden_deseado <- c ("Inflation", "Political extremism", "Crime or gun violence", "Immigration", "Climate change", "Government budget/debt",
                    "Abortion", "Race and racism", "Economic inequality", "Foreign conflicts or terrorism", "Healthcare",
                    "Election security", "Taxes", "Education", "Drug addiction", "COVID-19", "Unemployment", "Natural disasters")
datos_filtrados$Categoría <- factor(datos_filtrados$Categoría, levels = orden_deseado)


  # plot
f <- ggplot(datos_filtrados) +
  aes(x = Waves, y = Valores, fill = Categoría, alluvium = Categoría) +
  geom_alluvium(decreasing = FALSE, show.legend = FALSE, alpha = 0.95, colour = "white", size = 1.9) +
  scale_x_discrete(position = "top") +  
  scale_fill_manual(values = c("#1a40af", "#743f96", "#8f4683", "#9e5276", "#b16f63", "#a9606b", "#e7ea98", "#b67f5c", "#bdad53", "#ba8f57", "#bdbd54", "#bdcc59", "#ccf483", "#b7d051", "#c1e86f", "#bc9e54", "#f2f3e0", "#f2f3e0")) +
  labs(
    title = "Americans' top concern is still inflation",
    subtitle = "Share of Americans who said each issue was among the most important facing the\n country in six waves of a FiveThirtyEight/Ipsos survey, April-October 2022"
  ) +
  theme_minimal() +
  theme(
    axis.title.x.top = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x.top = element_text(angle = 0, hjust = 0.5, vjust = 0.5, size = 9, family = "Agency FB", face= "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    plot.margin = unit(c(1, 1, 1, 1), "lines"), 
    panel.grid.major.x = element_line(color = "black", size = 0.07),
    panel.grid.minor.x = element_line(color = "black", size = 0.07),
    plot.title = element_text(family = "Hansplatz Grotesk Bold", size = 13, face = "bold", hjust = 0, margin = margin(b = 10, unit = "pt")),  # Alineación a la izquierda y margen inferior
    plot.subtitle = element_text(family = "Hansplatz Grotesk Bold", size = 9, face = "plain", hjust = 0, margin = margin(t = 0, r = 0, b = 20, l = 0, unit = "pt"))  # Alineación a la izquierda, en dos líneas y margen inferior
  ) +
  coord_cartesian(xlim = c(NA, NA), expand = FALSE)  

f
  
  

# anotaciones

 f <- f+ annotate ("shadowText", x= 5.4, y=250, label= paste("INFLATION"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08) 
 
 f <- f + annotate (geom= "text", x= 5.8, y= 236, label = paste ("65 percent of survey respondents said inflation was",
                                                         "one of the most important issues facing the country,",
                                                         "the highest of any wave of this survey", sep = "\n"), family = "Franklin Gothic Medium", size= 2.7,colour= "white", hjust=1)
 
 f <- f+ annotate ("shadowText", x= 3.03547189834111, y= 191.940039688379, label= paste ("CRIME OR GUN VIOLENCE"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08 )
 
 f <- f+annotate ( "shadowText", x= 2.7681052384344, y = 159.126290409273, label =paste ("POLITICAL EXTREMISM"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08 )
 
 f <- f+annotate ( "shadowText", x=4.49832172596228, y = 139.615412459535, label = paste ("CLIMATE CHANGE"),  family= "Franklin Gothic Medium", size=  3.5, color= "black", bg.color= "white", bg.r= 0.08 )

 f <- f+ annotate ( "shadowText",x = 4.50788283594673, y = 121.878250687045, label = paste ("IMMIGRATION"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08 )
 
 f <- f+ annotate ("shadowText", x= 4.77559391551139, y = 103.02794700318, label = paste ("GOVERMENT BUDGET/DEBT"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x= 3.03040079654389, y = 130.400910778853, label = paste("ABORTION"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x= 3.40547189834111, y = 80.7433528761925, label= paste("RACE AND RACISM"), family= "Franklin Gothic Medium", size= 3.5, angle=-6L, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x= 1.50466965260073, y = 97.2508436873157, label= paste("FOREIGN"), family= "Franklin Gothic Medium", size= 3.5,angle= -35L, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x= 1.42134402562677, y = 90.9367782109428, label = paste ("CONFLICT OR "), family="Franklin Gothic Medium", size= 3.5, angle= -35L, vjust = 0.25, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x= 1.35965944508192, y = 87.1183131338777, label = paste ("TERRORISM"), family= "Franklin Gothic Medium", size= 3.5,angle= -35L, color= "black", bg.color= "white", bg.r= 0.08) 
 
 f <- f+ annotate ("shadowText", x= 3.97289956683296, y = 40.1741646222174, label = paste ("COVID-19"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08)

 f <- f+ annotate ("shadowText",x = 3.9202178680187, y = 52.7033197743356, label = paste("HEALTHCARE"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x=  4.46963839600892, y = 64.1996250727836, label = paste ("ECONOMIC INEQUALITY"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x= 1.7800952657120652, y = 27.3196877943721, label = paste ("ELECTION SECURITY"),family= "Franklin Gothic Medium", size= 3.3, angle= -7L, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x =5.35770595205863, y = 26.8394405136272, label = paste ("DRUG ADDICTION"),family= "Franklin Gothic Medium", size= 3.5, angle= -5L, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x = 5.10049440802788, y = 21.6345688058513, label = paste ("EDUCATION"),family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08)
 
 f <- f+ annotate ("shadowText", x = 5.75082486420105, y = 12.8789224437039, label = paste ("TAXES"), family= "Franklin Gothic Medium", size= 3.5, color= "black", bg.color= "white", bg.r= 0.08)

 f <- f+ annotate ("shadowText", x = 1.98660111783731, y = 4.08708463768002, label = paste ("UNEMPLOYMENT"),
                   family = "Franklin Gothic Medium", size = 3.3, color= "black",bg.color= "white", bg.r= 0.08)  
 f <- f+ annotate ("shadowText",x= 4.10927846574883, y = 2.98728980567533, label = paste ("NATURAL DISASTERS"), family= "Franklin Gothic Medium", size= 3.3, color= "black", bg.color= "white", bg.r= 0.08)

 f
 
 
 # improvement
 
 # Orden de categorías por la tendencia 
orden_tendencia <- datos_filtrados %>%
  group_by(Categoría) %>%
  summarise(Tendencia = sum(Valores)) %>%
  arrange(Tendencia) %>%
  pull(Categoría)

# Orden en la columna Categoría 
datos_filtrados$Categoría <- factor(datos_filtrados$Categoría, levels = orden_tendencia)

# Heatmap 
ggplot(datos_filtrados, aes(x = Waves, y = Categoría, fill = Valores)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  labs(
    title = "Americans' top concern's. April-October 2022",
    fill = NULL
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.title = element_blank(),
    plot.title = element_text(family= "Franklin Gothic Medium",hjust = 1, size = 12, margin = margin(b = 5, l = 10, unit = "pt")), # Título alineado a la izquierda con margen izquierdo
    plot.margin = margin(t = 10, r = 10, b = 10, l = 10, unit = "pt") # Ajustar márgenes del gráfico
  )





 


