---
title: "Post-COVID Wallet Woes: The High Cost of Living"
description: |
  COVID-19 had a major impact on the economy and effectively affected the consumption patterns of European households. 
categories: "2023"
author: Phong Duong
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

# Introduction

# Collecting and Processing Data

## Loading Packages

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(ggtext)
library(extrafont)
library(sysfonts)
library(showtext)
library(ggimage)
library(patchwork)
```

## Getting the data

```{r}
data <- read_csv("EU_data.csv.gz")
```

## Transforming data

```{r}
dataset <- data %>% 
  select(coicop, TIME_PERIOD, OBS_VALUE) %>% 
  mutate(coicop_name = case_when(
    coicop == "CP00" ~ "All-items HICP",
    coicop == "CP01" ~ "Food and non-alcoholic beverages",
    coicop == "CP02" ~ "Alcoholic beverages, tobacco and narcotics",
    coicop == "CP03" ~ "Clothing and footwear",
    coicop == "CP04" ~ "Housing, water and energy", #change to fit the graph
    coicop == "CP05" ~ "Household equipment and maintenance", #Change to fit the graph
    coicop == "CP06" ~ "Health",
    coicop == "CP07" ~ "Transport",
    coicop == "CP08" ~ "Communications",
    coicop == "CP09" ~ "Recreation and culture",
    coicop == "CP10" ~ "Education", 
    coicop == "CP11" ~ "Restaurants and hotels",
    coicop == "CP12" ~ "Miscellaneous goods and services"
    ),
    percent = OBS_VALUE / 1000 * 100) %>% 
  filter((!coicop %in% c("CP00")) & between(TIME_PERIOD, 2022, 2023)) %>% 
  select(coicop, coicop_name, TIME_PERIOD, percent)
```

# Replicating the Plot

# Alternative Graph
