---
title: "forest_plot"
format: html
editor: visual
---

```{r, fig.width=5, fig.height=6, dpi=300, dev='png'}
forest_full_results <- tabla_final_resultados |>
  left_join(df_remittances, by = "Country") |>
  left_join(df_answers, by = "Country") |>
  left_join(df_pop, by = "Country") |>
  rename(
    OR = Odds_Ratio,
    P_Value = P_Value,
    Remittances = Share,
    Respondents = people,
    Population = Population)


forest_full_results <- forest_full_results %>%
  mutate(
    text_style = case_when(
      Country %in% c("Urban Nigeria", "Rural Nigeria") ~ "italic", 
      Respondents > 2200 ~ "bold.italic", 
      Respondents >= 1500 & Respondents <= 2200 ~ "bold", 
      Respondents < 1500 ~ "plain", 
      TRUE ~ "plain"
    )
  )

forest_full_results <- forest_full_results %>%
  mutate(
    # Crear la columna P_Category basada en los umbrales de P_Value
    P_Category = case_when(
      P_Value < 0.001 ~ "very-low",      # p < 0.001
      P_Value < 0.01  ~ "low value",     # 0.001 <= p < 0.01
      P_Value < 0.05  ~ "medium",        # 0.01 <= p < 0.05
      TRUE            ~ "high"           # p >= 0.05 (El resto)
    )
  )

forest_full_results <- forest_full_results %>%
  mutate(
    P_Category = factor(
      P_Category, 
      levels = c("very-low", "low value", "medium", "high")
    )
  )
```

```{r}
forest_datos_ordenados <- forest_full_results %>%
  # Asegurarse de que el ordenamiento en Y (Country) sea el mismo que en el plot
  mutate(Country = factor(Country) %>% 
           fct_reorder(P_Value, .desc = TRUE)) %>%
  # Añadir la posición numérica (1, 2, 3...)
  mutate(y_pos = as.numeric(Country))
```


```{r}
forest_rectangulos <- forest_datos_ordenados %>%
  group_by(P_Category) %>%
  summarise(
    ymin = min(y_pos) - 0.5,  # 0.5 para empezar antes de la primera línea del grupo
    ymax = max(y_pos) + 0.5,  # 0.5 para terminar después de la última línea del grupo
    .groups = 'drop'
  ) %>%
  mutate(
    # Personalizar colores y transparencia según la categoría P_Category
    fill_color = case_when(
      P_Category == "very-low" ~ "#D9EDF7", # Azul muy claro
      P_Category == "low value" ~ "#F2DEDE", # Rojo muy claro
      P_Category == "medium" ~ "#FCF8E3",    # Amarillo muy claro
      TRUE ~ "#FFFFFF"                       # Blanco para 'high' (fondo)
    ),
    alpha_value = case_when(
      P_Category == "high" ~ 0, # Transparencia cero para el fondo
      TRUE ~ 0.5 # 50% de transparencia para las categorías importantes
    ),
    # Eje X: Cobre todo el rango visible del plot (ajusta xmin/xmax según tu escala OR)
    xmin = -Inf, # Empieza en el borde izquierdo del panel
    xmax = Inf   # Termina en el borde derecho del panel
  )
```

```{r, fig.width=5, fig.height=6, dpi=300, dev='png'}
forest_plot_final <- forest_full_results %>%
  
  # ORDENAMIENTO: Por P_Value, de MAYOR a MENOR (.desc = TRUE)
  # Usamos las columnas 'P_Value' y 'Country' directamente.
  mutate(Country = factor(Country) %>% 
           fct_reorder(P_Value, .desc = TRUE)) %>%
  
  # Gráfico: X=OR, Y=Country
  ggplot(aes(x = OR, y = Country)) +
  
  geom_rect_pattern(
    # Coordenadas estáticas (Mapeo de la zona P-Value > 0.5)
    aes(xmin = 0.5, xmax = 2, 
        ymin = 1, ymax = 8),
    
    # Fondo del patrón
    fill = "#456c73",
    alpha = 0.03,
    
    # Configuración del patrón
    pattern = 'none',          # Tipo de patrón: rayas diagonales

    # Borde: Usamos la línea discontinua de 0.5 que ya dibujaste, por lo que el borde de la caja puede ser transparente.
    colour = "transparent", 
    
    inherit.aes = FALSE # Esencial para geoms de patrón estático
) +
  
    geom_rect_pattern(
    # Coordenadas estáticas (Mapeo de la zona P-Value > 0.5)
    aes(xmin = 0.5, xmax = 2, 
        ymin = 8, ymax = 23),
    
    # Fondo del patrón
    fill = "#6197a0",
    alpha = 0.02,
    
    # Configuración del patrón
    pattern = 'none',          # Tipo de patrón: rayas diagonales

    # Borde: Usamos la línea discontinua de 0.5 que ya dibujaste, por lo que el borde de la caja puede ser transparente.
    colour = "transparent", 
    
    inherit.aes = FALSE # Esencial para geoms de patrón estático
) +
  
      geom_rect_pattern(
    # Coordenadas estáticas (Mapeo de la zona P-Value > 0.5)
    aes(xmin = 0.5, xmax = 2, 
        ymin = 23, ymax = 28),
    
    # Fondo del patrón
    fill = "#b9e8ef",
    alpha = 0.03,
    
    # Configuración del patrón
    pattern = 'none',          # Tipo de patrón: rayas diagonales

    # Borde: Usamos la línea discontinua de 0.5 que ya dibujaste, por lo que el borde de la caja puede ser transparente.
    colour = "transparent", 
    
    inherit.aes = FALSE # Esencial para geoms de patrón estático
) +
  
        geom_rect_pattern(
    # Coordenadas estáticas (Mapeo de la zona P-Value > 0.5)
    aes(xmin = 0.5, xmax = 2, 
        ymin = 28, ymax = 32),
    
    # Fondo del patrón
    fill = "#dcf3f7",
    alpha = 0.11,
    
    # Configuración del patrón
    pattern = 'none',          # Tipo de patrón: rayas diagonales

    # Borde: Usamos la línea discontinua de 0.5 que ya dibujaste, por lo que el borde de la caja puede ser transparente.
    colour = "transparent", 
    
    inherit.aes = FALSE # Esencial para geoms de patrón estático
) +
  
        geom_rect_pattern(
    # Coordenadas estáticas (Mapeo de la zona P-Value > 0.5)
    aes(xmin = 0.5, xmax = 2, 
        ymin = 32, ymax = 36),
    
    # Fondo del patrón
    fill = "#e8f7fa",
    alpha = 0.15,
    
    # Configuración del patrón
    pattern = 'none',          # Tipo de patrón: rayas diagonales

    # Borde: Usamos la línea discontinua de 0.5 que ya dibujaste, por lo que el borde de la caja puede ser transparente.
    colour = "transparent", 
    
    inherit.aes = FALSE # Esencial para geoms de patrón estático
) +

  # A. Puntos (Odds Ratio) - Color mapeado a la intensidad de Remittances
  # Usamos la columna 'Remittances' directamente para el color.
  geom_point(
    aes(color = Remittances), 
    size = 4,
    shape = 16
  ) +
  
  # B. Línea de No Efecto (OR = 1)
  geom_vline(xintercept = 1, linetype = "dashed", color = "red", size = 0.4) +
  
  geom_hline(
    data = lineas_p_value, 
    aes(yintercept = y_interseccion),
    linetype = "dotted",
    color = "gray30",
    size = 0.5
  ) +
  
  geom_text(
      # Colocar el texto a la izquierda del punto de quiebre (0.5)
      aes(x = 0.495, label = Country, fontface = text_style), 
      hjust = 1, # Alineación a la derecha (para pegarse a x=0.45)
      size = 6,
      color = "black",
      family = "Barlow"
  ) +
  
  # C. Escala Logarítmica en el Eje X
  scale_x_log10(
    name = "Odds Ratio (OR)",
    breaks = c(0.5, 1, 1.5, 2, 3), 
    labels = c("0.5", "1", "1.5", "2", "3")
  ) +
  
  # D. Escala de Color Continuo (Intensidad de Remesas)
  scale_color_gradient(
    low = "#F6D2CB",          # Menos intenso
    high = "#7D6892",         # Más intenso
    name = "Share of people who\nreceive remiitances"
  ) +

  # E. Tema y Estilos
  labs(
    title = "Does hunger make Africans want to move abroad?",
    subtitle = "Extensive survey data shows that there is not a simple answer",
    y = NULL
  ) +
  
  coord_cartesian(
    xlim = c(0.5, 2), # Ajusta el rango visible del eje X
    clip = "off"     # CRÍTICO: Permite que geom_text se salga de los límites del panel
  ) +
  
theme_minimal() + 
  theme(
    plot.title = element_text(
        face = "bold",          # Estilo de la fuente (bold, italic, plain)
        size = 25,              # Tamaño de la fuente (puedes usar 16, 18, 20, etc.)
        hjust = 0               # Alineación (0 = izquierda, 0.5 = centro, 1 = derecha)
    ),
    
    # 2. Ajustar el SUBTÍTULO
    plot.subtitle = element_text(
        size = 20,              # Tamaño de la fuente (generalmente más pequeño que el título)
        hjust = 0,
        margin = margin(b = 10) # Añadir un poco de margen inferior para separarlo del plot
    ),
    
    legend.title = element_text(size = 14, face = "bold"), # Tamaño del título (ej. "Remesas (%)")
    legend.text = element_text(size = 12),                 # Tamaño de las etiquetas (ej. los números 10, 20, 30)

    # 2. Reducir el espacio vertical entre las líneas de la leyenda
    legend.spacing.y = unit(0.01, "cm"),                    # Reduce el espacio entre entradas (0.1cm es pequeño)
    
    # Si la leyenda tiene varias filas, también puedes ajustar:
    legend.spacing.x = unit(0.5, "cm"),
    
    # Si el elemento es un cuadro (como la leyenda de fondo P-Value)
    # y el título está muy separado:
    legend.title.position = "top",
    
    legend.position = "bottom",
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank(),
    panel.grid.minor = element_blank(),
    plot.margin = margin(
        t = 10, 
        r = 10, 
        b = 10, 
        l = 50, 
        unit = "pt"
    ) 
  )

print(forest_plot_final)
```


