---
title: "Leyends"
format: html
editor: visual
---

```{r, fig.width=1.17, fig.height=3.2, dpi=500, dev='png'}
library(dplyr)
library(stringr)

# 1. DATAFRAME FOR THE LEGEND
remittance_data <- data.frame(
  percent = remittance_groups_levels,
  # Asignar la posición Y de forma inversa (el más alto va primero)
  y = length(remittance_groups_levels):1)

remittance_data <- remittance_data %>%
  mutate(
    fill_color = remittance_colors[percent], 
    border_color = border_colors[percent]) %>%
  mutate(
    fill_color = as.character(fill_color),
    border_color = as.character(border_color))

remittance_groups_levels <- c("> 40%", "35-40%", "30-35%", "25-30%", "20-25%", 
                               "15-20%", "10-15%", "< 10%")

## SETTING AESTHETICS OF THE LEGEND
y_step <- 0.37
num_items <- length(remittance_groups_levels)

remittance_data <- data.frame(
  percent_raw = remittance_groups_levels,
  y = seq(from = num_items * y_step, 
          to = y_step, 
          by = -y_step)) %>%
  mutate(
  percent_label = case_when(
    percent_raw == "> 40%" ~ "40%",
    percent_raw == "35-40%" ~ "35%",
    percent_raw == "30-35%" ~ "30%",
    percent_raw == "25-30%" ~ "25%",
    percent_raw == "20-25%" ~ "20%",
    percent_raw == "15-20%" ~ "15%",
    percent_raw == "10-15%" ~ "10%",
    TRUE ~ NA_character_)) %>%
  mutate(
    fill_color = remittance_colors[percent_raw], 
    border_color = border_colors[percent_raw]) %>%
  mutate(
    fill_color = as.character(fill_color),
    border_color = as.character(border_color))

line_data <- data.frame(
  y = seq(from = (num_items - 1) * y_step + y_step / 2, 
          to = y_step * 1.5,                             
          by = -y_step))

explanatory_text <- "If more people receive\nmoney transfers from\nrelatives or friends\nabroad, it probably\nmeans that emigration\nis more widespread—\nand thereby more\nrelatable as a possible\nway of hardship. If\nemigration is rare, it\nmight be more of\nanelite phenomenon,\nbeyond the imagination\nof those who experience\nhunger."


# CREATION GRAPH

p_legend_remittance <- ggplot() +
  
  # A. LÍNEAS HORIZONTALES SEPARADORAS (Entre los círculos)
  geom_segment(data = line_data, aes(x = 0.18, y = y + 0.42, xend = 0.28, yend = y + 0.42),
               linewidth = 0.15, color = "black", inherit.aes = FALSE) +
  
  # B. CÍRCULOS DE REMESAS Y ETIQUETAS
  geom_point(data = remittance_data, aes(x = 0.25, y = y+0.4, fill = fill_color, color = border_color),
             shape = 21, size = 3, linewidth = 0.5) + 
  
  geom_text(data = remittance_data, aes(x = 0.05, y = y + 0.24, label = percent_label),
            hjust = 0, size = 9, family = "Barlow") +
  
  # C. TÍTULO Y LÍNEA DIVISORIA DE TÍTULO
  geom_text(aes(x = 0.07, y = 4.1, label = "Share of people\nwho receive\nremittances"), 
            vjust= 0.7, hjust = 0, lineheight = 0.2, fontface = "bold", size = 11, family = "Barlow") +
  
  geom_segment(aes(x = 0.05, y = 3.55, xend = 1.15, yend = 3.55), vjust = 0,
               linewidth = 0.4, color = "black") + 
  
  # D. TEXTO EXPLICATORIO 
  geom_text(aes(x = 0.4, y = 2.2, label = explanatory_text), 
            hjust = 0, vjust = 0.6, lineheight = 0.13, fontface= "plain", size = 12, color = "gray50", family = "Caveat") +

  # E. CONFIGURACIÓN FINAL
  scale_fill_identity() + 
  scale_color_identity() + 
  
  coord_cartesian(
    xlim = c(0, 1.2), 
    ylim = c(0, 4.2), 
    clip = "off") +
  
theme_void() + 
  theme(
    plot.margin = margin(0.0, 0, 0, 0, unit = "cm"),
    plot.title = element_text(margin = margin(0, 0, 0, 0, unit = "pt")))
```

```{r}
p_combined <- p_main + theme(
    # Aumentar el margen izquierdo para el título/etiqueta
    plot.margin = margin(t = 5, r = 5, b = 5, l = 20) # Aumentar 'l' (izquierda)
)
```


```{r, fig.width=8.7, fig.height=10, dpi=500, dev='png'}
library(patchwork)

p_respondents <- ggplot() + 
  theme_void() + 
  theme(plot.margin = margin(0, 0, 0, 0, "pt")) 

p_legend_size <- ggplot() + 
  theme_void() + 
  theme(plot.margin = margin(0, 0, 0, 0, "pt")) 

p_sources <- ggplot() + 
  theme_void() + 
  theme(plot.margin = margin(0, 0, 0, 0, "pt"))

bottom_row_final <- (p_respondents | p_legend_size | p_legend_remittance | p_sources) +
  plot_layout(widths = c(
    1.45,
    1.45,
    1.4,  
    4.5     
  )) +
  theme(
    panel.spacing = unit(0, "pt"))

final_plot <- p_combined / bottom_row_final

final_plot <- final_plot +
  plot_layout(heights = c(5, 2)) +
  plot_annotation(theme = theme(plot.margin = margin(t = 5, r = 5, b = 5, l = 5)) & 
  theme(plot.margin = margin(t = 5, r = 5, b = 5, l = 5)))

final_plot
```


```{r}

ggsave(
    filename = "grafico.png", # Nombre del archivo y extensión
    plot = final_plot,                       # Usa tu variable 'p'
    device = "png",                # Especifica el formato JPG
    width = 7,                     # Ancho (ajusta si es necesario)
    height = 8,                    # Alto (ajusta si es necesario)
    units = "in",                   # Unidades (pulgadas)
    dpi = 600                       # Resolución
)
```


